<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="author" content="Ozancan Ozdemir" />


<meta name="progressive" content="false" />
<meta name="allow-skip" content="false" />
<meta name="learnr-version-prerender" content="0.11.2" />

<title>STAT 412-Recitation 1</title>

<!-- header-includes START -->
<!-- HEAD_CONTENT -->
<!-- header-includes END -->
<!-- HEAD_CONTENT -->

<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>


<!-- taken from https://github.com/rstudio/rmarkdown/blob/de8a9c38618903627ca509f5401d50a0876079f7/inst/rmd/h/default.html#L293-L343 -->
<!-- tabsets -->
<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>
<!-- end tabsets -->


</head>

<body>
<a class='sr-only sr-only-focusable visually-hidden-focusable' href='#learnr-tutorial-content'>Skip to Tutorial Content</a>



<div class="pageContent band">
<main class="bandContent page">

<article class="topics" id="learnr-tutorial-content">

<div id="section-introduction" class="section level2">
<h2><span style="color:darkred">Introduction</span></h2>
<p>In this part, we will go through some basic definitions as a
reminder.</p>
<p><img
src="https://onuduymustum.com/wp-content/uploads/kimse-bir-sey-bilmiyorsa-bir-insan-her-seyi-bilebilir.jpg"
style="width:60.0%" /></p>
<div id="section-what-is-statistics" class="section level3">
<h3><span style="color:darkred"><strong>What is
Statistics?</strong></span></h3>
<p>Data is a collection of information collected by observations,
measurements, research or analysis. One of the main characteristics of
today’s world is to be data generative. According to the estimates, at
least <strong>2.5 quintillion bytes</strong> of data is produced every
day.</p>
<p><strong>Question : How to make such an amount of data
valuable?</strong></p>
<p><strong>Answer: Statistics!</strong></p>
<div id="section-what-is-statistics-1" class="section level4">
<h4><strong>What is Statistics?</strong></h4>
<p>There are several definitions of statistics in the literature.</p>
<p><strong>Definition 1:</strong></p>
<ul>
<li><p><strong>Formally:</strong> “Statistics” is the science of
learning from data, and of measuring, controlling and communicating
uncertainty. (American Statistical Association (ASA))</p></li>
<li><p><strong>Informally:</strong> Statistics is the art of learning
from data.</p></li>
</ul>
<p>There are mainly two forms of the statistics.</p>
<ul>
<li><p><strong>Descriptive Statistics</strong> is primarily about
summarizing a given data set through numerical summaries and graphs, and
can be used for exploratory analysis to visualize the information
contained in the data and suggest hypotheses etc.</p></li>
<li><p><strong>Inferential Statistics</strong> is concerned with methods
for making conclusions about a population using information from a
sample, and assessing the reliability of, and uncertainty in, these
conclusions.</p></li>
</ul>
</div>
</div>
<div id="section-data-and-data-types" class="section level3">
<h3><span style="color:darkred"><strong>Data and Data
Types</strong></span></h3>
<p>The data types or groups are an important concept of statistics,
which needs to be understood, to correctly apply statistical analysis to
your data and therefore to correctly conclude certain assumptions about
it.</p>
<ul>
<li><p><strong>Data</strong> is plural of datum which is an
abstraction.</p></li>
<li><p><strong>Datum</strong> is a single quantity or quality of a
real-world entity such as person, object and event.</p></li>
<li><p><strong>A data set</strong> consists of the data related to a
collection of entities which are described in terms of a set of
attributes.</p></li>
</ul>
<p>Both <strong>data</strong> and <strong>data set</strong> can be
categorized into several groups.</p>
<p>The data types or groups are an important concept of statistics,
which needs to be understood, to correctly apply statistical
measurements to your data and therefore to correctly conclude certain
assumptions about it.</p>
<p>Understanding data types results in doing exploratory data analysis
which the one of the important of the data analysis project.</p>
<p>In general attribute, we can divide data as</p>
<ul>
<li><p><span style="color:darkred"><strong>Quantitative
data</strong></span> deals with numbers and things you can measure
objectively: dimensions such as height, width, and length.</p></li>
<li><p><span style="color:darkred"><strong>Qualitative
data</strong></span> data deals with characteristics and descriptors
that can’t be easily measured, but can be observed subjectively: smells,
tastes.</p></li>
</ul>
<p>These two data attributes have <strong>subgroups.</strong></p>
<div id="section-quantitative-attribute" class="section level4">
<h4><span style="color:darkred"><strong>Quantitative
Attribute</strong></span></h4>
<ul>
<li><p><strong>Discrete Data:</strong> We speak of discrete data if its
values are distinct and separate. In other words: We speak of discrete
data if the data can only take on certain values. This type of data can
not be <strong>measured but it can be counted.</strong> For example,
<strong>Number of defective item in a box</strong>, <strong>Number of
children in a household</strong>.</p></li>
<li><p><strong>Continuous Data:</strong> Continuous Data represents
measurements and therefore their values cannot be counted but they can
be measured. For example, <strong>temperature, height, or
weight</strong>.</p></li>
<li><p><strong>Interval Data</strong> Interval values represent ordered
units that have the same difference. Therefore we speak of interval data
when we have a variable that contains numeric values that are ordered
and where we know the exact differences between the values. It can be
either discrete or continious.</p></li>
</ul>
<p>The problem about the interval data is zero have no real meaning.
That’s why a lot of descriptive and inferential statistics cannot be
applied. For example, <strong>Temperature</strong>.</p>
<ul>
<li><strong>Ratio Data :</strong> Ratio values are also ordered units
that have the same difference. Ratio values are the same as interval
values, with the difference that they do have an absolute zero. In other
words, zero has its real meaning. For example, <strong>age,
distance</strong></li>
</ul>
<p><span style="color:darkred"><strong>Qualitative
Attribute</strong></span></p>
<ul>
<li><p><strong>Nominal Data:</strong> Nominal values represent discrete
units and are used to label variables, that have no quantitative value.
Just think of them as labels. Note that nominal data that has no order.
For example, <strong>Gender: Male, Female</strong></p></li>
<li><p><strong>Binary Data:</strong></p>
<p><strong>Ordinal Data:</strong> Ordinal values represent discrete and
ordered units. As you would guess from it’s name, order have an
importance. For example,</p></li>
<li><p>1- Totally disagree.</p></li>
<li><p>2- Disagree.</p></li>
<li><p>3- Neither agree nor disagree.</p></li>
<li><p>4- Agree.</p></li>
<li><p>5- Totally Agree.</p></li>
</ul>
<p>We can also categorized data set types into several groups, For
example,</p>
<ul>
<li><p><strong>Cross-Sectional:</strong> It is a collection of
observations (behaviours) for multiple subjects(entities) at single
point in time.</p></li>
<li><p><strong>Time Series:</strong> It is a collection of observations
(behaviours) for a single subject(entity) at different time intervals
(generally equally spaced)</p></li>
<li><p><strong>Panel Data:</strong> It is usually called as
Cross-sectional Time-series data as it a combination of above mentioned
types, i.e., collection of observations for multiple subjects at
different time points.</p></li>
<li><p><strong>Circular Data:</strong> It is the data that is measured
on a circle in degrees or radians.</p></li>
<li><p><strong>Image Data:</strong> Image data refers to a collection of
numerical values that represent the colors and intensities of pixels in
an image.</p></li>
</ul>
<p>and more…</p>
</div>
</div>
</div>
<div id="section-exploratory-data-analysis-eda" class="section level2">
<h2><span style="color:darkred"><strong>Exploratory Data Analysis
(EDA)</strong></span></h2>
<p>It is a process of exploring your data set through some techniques
such as visualization, transformation etc. It is called EDA.</p>
<p>It has a iterative form.</p>
<ul>
<li><p>Generate questions about your data, called developing research
questions<strong>(RQ)</strong>.</p></li>
<li><p>Search for answers by visualizing, transforming, and modelling
your data.</p></li>
<li><p>Use what you learn to refine your questions and/or generate new
questions.</p></li>
</ul>
<p>The main purpose behind EDA is understand your data and draw a
pattern for your upcoming analysis. In this process, a researcher should
<strong>feel free</strong> to investigate every idea. In other words,
EDA does not have any certain frame or rules. Thus, some of your idea
will be dead and some of them will be alive after this which makes it an
iterative process.</p>
<p>The easiest way of doing EDA is to use questions as a guide of your
investigation. Although EDA does not have any certain rules, there are
some suggestions while generating a question because you can generate
large amount of quantity by asking a qualified question. It also narrows
down a broad topic of interest into specific area of study.</p>
<p><strong>Two types</strong> question will be useful while discovering
your data.</p>
<ul>
<li><p>What type of variation occurs within variable?</p></li>
<li><p>What type of covariance occurs between variables?</p></li>
</ul>
<p>However, you should consider more details to develop well research
questions.</p>
<p>As data and data types, RQ can be classified into different
categories based on type of research to be done, which are quantitative
research, qualitative research and mixed.</p>
<p><span style="color:orange"><strong>Quantitative Research &amp;
Questions</strong></span></p>
<p>It includes the population to be studied, dependent and independent
variables, and the research design to be used. They are not answerable
with Yes and No which results in such questions do not have words such
as <strong>Is, Are, Do, Does</strong>.</p>
<p>It can be further categorized into three types: descriptive,
comparative, and relationship.</p>
<ul>
<li><p><strong>Descriptive research questions</strong> aim to measure
the responses of a studys population to one or more variables or
describe variables that the research will measure. These questions
typically begin with what.</p></li>
<li><p><strong>Comparative research questions</strong> aim to discover
the differences between two or more groups for an outcome variable.
These questions can be causal, as well. For instance, the researcher may
compare a group where a certain variable is involved and another group
where that variable is not present.</p></li>
<li><p><strong>Relationship research questions</strong> seek to explore
and define trends and interactions between two or more variables. These
questions often include both dependent and independent variables and use
words such as association or trends.</p></li>
</ul>
<p><span style="color:orange"><strong>Qualitative Research &amp;
Questions</strong></span></p>
<p>These questions generally aim to discover, explain, or explore. They
have also subgroups. Here are some of them.</p>
<ul>
<li><p>Descriptive research questions attempt to describe a
phenomenon.</p></li>
<li><p>Explanatory research questions seek to expound on a phenomenon or
examine reasons for and associations between what exists.</p></li>
<li><p>Ideological research questions are used in research that aims to
advance specific ideologies of a position.</p></li>
</ul>
<p>You can investigate some examples for quantitative and qualitative
research questions.</p>
<div class="figure">
<img src="http://users.metu.edu.tr/ozancan/table.png"
style="width:70.0%" alt="" />
<p class="caption">Example for RQs</p>
</div>
<p>To understand the details of constructing an appropriate research
question, you can have a look at the <a
href="https://www.guide2research.com/research/how-to-write-a-research-question">blog.</a></p>
<div class="panel-heading tutorial-quiz-title"><span data-i18n="text.quiz">Quiz</span></div>
<div class="panel panel-default tutorial-question-container">
<div data-label="quiz1-1" class="tutorial-question panel-body">
<div id="quiz1-1-answer_container" class="shiny-html-output"></div>
<div id="quiz1-1-message_container" class="shiny-html-output"></div>
<div id="quiz1-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<p>In data mining approach, EDA can be cross-classified into two
ways.</p>
<ul>
<li><strong>Numerical and Graphical</strong></li>
</ul>
<p>Numerical means that you are investigating the variable/s using
descriptive statistics like mean, standard deviation, median and
IQR.</p>
<p>Graphical implies that you are using plots to explore the properties
of the variable/s.</p>
<ul>
<li><strong>Univariate and Multivariate</strong></li>
</ul>
<p>Univariate means that you are investigating one variable.</p>
<p>Multivariate means that you are handling with two or more variables.
Usually, two variables are considered in the multivariate EDA.</p>
<p><strong>It is recommended to perform Univariate EDA, before applying
multivariate EDA.</strong></p>
</div>
<div id="section-application" class="section level2">
<h2><span style="color:darkred"><strong>Application</strong></span></h2>
<p>Please install</p>
<ul>
<li><p><code>summarytools</code></p></li>
<li><p><code>Desctools</code></p></li>
<li><p><code>table1</code></p></li>
<li><p><code>lattice</code></p></li>
<li><p><code>ggplot2</code> (It is used for the example
dataset.)</p></li>
<li><p><code>Hmisc</code></p></li>
<li><p><code>psych</code></p></li>
</ul>
<p>Throughout this class, we will be working with the
<strong>diamonds</strong> dataset, It is a dataset that comes with the
ggplot2 package, which means it is readily available for use. Let’s take
some time to become acquainted with the dataset.</p>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["carat"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["cut"],"name":[2],"type":["ord"],"align":["right"]},{"label":["color"],"name":[3],"type":["ord"],"align":["right"]},{"label":["clarity"],"name":[4],"type":["ord"],"align":["right"]},{"label":["depth"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["table"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["price"],"name":[7],"type":["int"],"align":["right"]},{"label":["x"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["y"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["z"],"name":[10],"type":["dbl"],"align":["right"]}],"data":[{"1":"0.23","2":"Ideal","3":"E","4":"SI2","5":"61.5","6":"55","7":"326","8":"3.95","9":"3.98","10":"2.43"},{"1":"0.21","2":"Premium","3":"E","4":"SI1","5":"59.8","6":"61","7":"326","8":"3.89","9":"3.84","10":"2.31"},{"1":"0.23","2":"Good","3":"E","4":"VS1","5":"56.9","6":"65","7":"327","8":"4.05","9":"4.07","10":"2.31"},{"1":"0.29","2":"Premium","3":"I","4":"VS2","5":"62.4","6":"58","7":"334","8":"4.20","9":"4.23","10":"2.63"},{"1":"0.31","2":"Good","3":"J","4":"SI2","5":"63.3","6":"58","7":"335","8":"4.34","9":"4.35","10":"2.75"},{"1":"0.24","2":"Very Good","3":"J","4":"VVS2","5":"62.8","6":"57","7":"336","8":"3.94","9":"3.96","10":"2.48"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre><code>library(ggplot2)
head(diamonds)</code></pre>
<p><span style="color:darkred"><strong>The columns
expressions</strong></span></p>
<table>
<colgroup>
<col width="8%" />
<col width="91%" />
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Expression</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>price</td>
<td>price in US dollars <span
class="math inline">\(\$326-\$18,823\)</span></td>
</tr>
<tr class="even">
<td>carat</td>
<td>weight of the diamond 0.2-5.01</td>
</tr>
<tr class="odd">
<td>cut</td>
<td>quality of the cut Fair, Good, Very Good, Premium, Ideal</td>
</tr>
<tr class="even">
<td>color</td>
<td>diamond color J (worst) to D (best)</td>
</tr>
<tr class="odd">
<td>clarity</td>
<td>measurement of how clear the diamond is I1 (worst), SI2, SI1, VS2,
VS1, VVS2, VVS1, IF (best)</td>
</tr>
<tr class="even">
<td>x</td>
<td>length in mm 0-10.74</td>
</tr>
<tr class="odd">
<td>y</td>
<td>width in mm 0-58.9</td>
</tr>
<tr class="even">
<td>z</td>
<td>depth in mm 0-31.8 depth</td>
</tr>
<tr class="odd">
<td>total</td>
<td>depth percentage 43-79</td>
</tr>
<tr class="even">
<td>table</td>
<td>width of top of diamond relative to widest point</td>
</tr>
</tbody>
</table>
<p>We can use <code>dim()</code> command to extract the dimension of the
dataset.</p>
<pre><code>dim(diamonds)</code></pre>
<pre><code>## [1] 53940    10</code></pre>
<p>This dataset contains information about 53,940 round-cut diamonds
measured by 10 variables.</p>
<p>After this, we should check the class of the variables. The checking
the class of variables in R is an essential step before proceeding to
the analysis, because wrong class type may affect your analysis
negatively.</p>
<pre><code>str(diamonds)</code></pre>
<pre><code>## tibble [53,940 x 10] (S3: tbl_df/tbl/data.frame)
##  $ carat  : num [1:53940] 0.23 0.21 0.23 0.29 0.31 0.24 0.24 0.26 0.22 0.23 ...
##  $ cut    : Ord.factor w/ 5 levels &quot;Fair&quot;&lt;&quot;Good&quot;&lt;..: 5 4 2 4 2 3 3 3 1 3 ...
##  $ color  : Ord.factor w/ 7 levels &quot;D&quot;&lt;&quot;E&quot;&lt;&quot;F&quot;&lt;&quot;G&quot;&lt;..: 2 2 2 6 7 7 6 5 2 5 ...
##  $ clarity: Ord.factor w/ 8 levels &quot;I1&quot;&lt;&quot;SI2&quot;&lt;&quot;SI1&quot;&lt;..: 2 3 5 4 2 6 7 3 4 5 ...
##  $ depth  : num [1:53940] 61.5 59.8 56.9 62.4 63.3 62.8 62.3 61.9 65.1 59.4 ...
##  $ table  : num [1:53940] 55 61 65 58 58 57 57 55 61 61 ...
##  $ price  : int [1:53940] 326 326 327 334 335 336 336 337 337 338 ...
##  $ x      : num [1:53940] 3.95 3.89 4.05 4.2 4.34 3.94 3.95 4.07 3.87 4 ...
##  $ y      : num [1:53940] 3.98 3.84 4.07 4.23 4.35 3.96 3.98 4.11 3.78 4.05 ...
##  $ z      : num [1:53940] 2.43 2.31 2.31 2.63 2.75 2.48 2.47 2.53 2.49 2.39 ...</code></pre>
<p>To find out the class of a specific variable, you can use
<code>class()</code> command.</p>
<pre><code>class(diamonds$price) #class function show the class of a variable </code></pre>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<p>You can check whether the variable belongs to a specific class using
<code>is.classname()</code> type function.</p>
<pre><code>is.factor(diamonds$price)</code></pre>
<pre><code>## [1] FALSE</code></pre>
<pre><code>is.integer(diamonds$price)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>You can change the class of object to the desired one by
<code>as.</code> type functions.</p>
<pre><code>a&lt;-as.factor(diamonds$price)
is.factor(a)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p><span style="color:darkred"><strong>Numerical Summary of
Data</strong></span></p>
<p>The information that gives a quick and simple description of the data
including mean, median, mode, minimum value, maximum value, range,
standard deviation, etc are called summary statistics. It is an
essential step to identify the certain pattern of your dataset like the
presence of the missing observations or outliers. Looking at the
descriptive statistics of all the data can also serve as a source for
generating research questions.</p>
<p>The easiest way to obtain of summary statistics of the variables in
the dataset is to use Rs base <code>summary()</code> function whose
output is not very nice.</p>
<p>You will get the mean, quantiles, and min/max for numeric variables,
and get frequency table for categorical one, but thats all.</p>
<pre><code>summary(diamonds)</code></pre>
<pre><code>##      carat               cut        color        clarity          depth      
##  Min.   :0.2000   Fair     : 1610   D: 6775   SI1    :13065   Min.   :43.00  
##  1st Qu.:0.4000   Good     : 4906   E: 9797   VS2    :12258   1st Qu.:61.00  
##  Median :0.7000   Very Good:12082   F: 9542   SI2    : 9194   Median :61.80  
##  Mean   :0.7979   Premium  :13791   G:11292   VS1    : 8171   Mean   :61.75  
##  3rd Qu.:1.0400   Ideal    :21551   H: 8304   VVS2   : 5066   3rd Qu.:62.50  
##  Max.   :5.0100                     I: 5422   VVS1   : 3655   Max.   :79.00  
##                                     J: 2808   (Other): 2531                  
##      table           price             x                y         
##  Min.   :43.00   Min.   :  326   Min.   : 0.000   Min.   : 0.000  
##  1st Qu.:56.00   1st Qu.:  950   1st Qu.: 4.710   1st Qu.: 4.720  
##  Median :57.00   Median : 2401   Median : 5.700   Median : 5.710  
##  Mean   :57.46   Mean   : 3933   Mean   : 5.731   Mean   : 5.735  
##  3rd Qu.:59.00   3rd Qu.: 5324   3rd Qu.: 6.540   3rd Qu.: 6.540  
##  Max.   :95.00   Max.   :18823   Max.   :10.740   Max.   :58.900  
##                                                                   
##        z         
##  Min.   : 0.000  
##  1st Qu.: 2.910  
##  Median : 3.530  
##  Mean   : 3.539  
##  3rd Qu.: 4.040  
##  Max.   :31.800  
## </code></pre>
<p><span style="color:darkred"> Interpretation </span></p>
<p>The average of carat concentration is 0.8. The minimum of carat is
0.2, while its maximum is 5. The half of the carat is below or above
0.7. 25% of the carat is below 0.4 and above 1.04. Lastly, it can be
said that the variable might have outlier observations since there is a
considerable difference between third quartile and maximum value, which
also indicates that the distribution of carat may seem right skewed.</p>
<p>Also, out of 53940 diamonds, 1610 of them have fair cut, 4906 of them
good cut, 21551 of them have ideal, 13791 of them have premium cut and
12082 of them very good cut.</p>
<p>The output of <code>summary</code> does not provide other useful
statistics such as standard deviation or IQR, which are used to measure
the spread. To spot more descriptive statistics, you should consider
some additional packages. For example,</p>
<pre><code>summarytools::descr(diamonds)</code></pre>
<pre><code>## Non-numerical variable(s) ignored: cut, color, clarity</code></pre>
<pre><code>## Descriptive Statistics  
## diamonds  
## N: 53940  
## 
##                        carat      depth      price      table          x          y          z
## ----------------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
##              Mean       0.80      61.75    3932.80      57.46       5.73       5.73       3.54
##           Std.Dev       0.47       1.43    3989.44       2.23       1.12       1.14       0.71
##               Min       0.20      43.00     326.00      43.00       0.00       0.00       0.00
##                Q1       0.40      61.00     950.00      56.00       4.71       4.72       2.91
##            Median       0.70      61.80    2401.00      57.00       5.70       5.71       3.53
##                Q3       1.04      62.50    5324.50      59.00       6.54       6.54       4.04
##               Max       5.01      79.00   18823.00      95.00      10.74      58.90      31.80
##               MAD       0.47       1.04    2475.94       1.48       1.38       1.36       0.85
##               IQR       0.64       1.50    4374.25       3.00       1.83       1.82       1.13
##                CV       0.59       0.02       1.01       0.04       0.20       0.20       0.20
##          Skewness       1.12      -0.08       1.62       0.80       0.38       2.43       1.52
##       SE.Skewness       0.01       0.01       0.01       0.01       0.01       0.01       0.01
##          Kurtosis       1.26       5.74       2.18       2.80      -0.62      91.20      47.08
##           N.Valid   53940.00   53940.00   53940.00   53940.00   53940.00   53940.00   53940.00
##         Pct.Valid     100.00     100.00     100.00     100.00     100.00     100.00     100.00</code></pre>
<pre><code>Hmisc::describe(diamonds)</code></pre>
<pre><code>## diamonds 
## 
##  10  Variables      53940  Observations
## --------------------------------------------------------------------------------
## carat 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##    53940        0      273    0.999   0.7979   0.5122     0.30     0.31 
##      .25      .50      .75      .90      .95 
##     0.40     0.70     1.04     1.51     1.70 
## 
## lowest : 0.20 0.21 0.22 0.23 0.24, highest: 4.00 4.01 4.13 4.50 5.01
## --------------------------------------------------------------------------------
## cut 
##        n  missing distinct 
##    53940        0        5 
## 
## lowest : Fair      Good      Very Good Premium   Ideal    
## highest: Fair      Good      Very Good Premium   Ideal    
##                                                             
## Value           Fair      Good Very Good   Premium     Ideal
## Frequency       1610      4906     12082     13791     21551
## Proportion     0.030     0.091     0.224     0.256     0.400
## --------------------------------------------------------------------------------
## color 
##        n  missing distinct 
##    53940        0        7 
## 
## lowest : D E F G H, highest: F G H I J
##                                                     
## Value          D     E     F     G     H     I     J
## Frequency   6775  9797  9542 11292  8304  5422  2808
## Proportion 0.126 0.182 0.177 0.209 0.154 0.101 0.052
## --------------------------------------------------------------------------------
## clarity 
##        n  missing distinct 
##    53940        0        8 
## 
## lowest : I1   SI2  SI1  VS2  VS1 , highest: VS2  VS1  VVS2 VVS1 IF  
##                                                           
## Value         I1   SI2   SI1   VS2   VS1  VVS2  VVS1    IF
## Frequency    741  9194 13065 12258  8171  5066  3655  1790
## Proportion 0.014 0.170 0.242 0.227 0.151 0.094 0.068 0.033
## --------------------------------------------------------------------------------
## depth 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##    53940        0      184    0.999    61.75    1.515     59.3     60.0 
##      .25      .50      .75      .90      .95 
##     61.0     61.8     62.5     63.3     63.8 
## 
## lowest : 43.0 44.0 50.8 51.0 52.2, highest: 72.2 72.9 73.6 78.2 79.0
## --------------------------------------------------------------------------------
## table 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##    53940        0      127     0.98    57.46    2.448       54       55 
##      .25      .50      .75      .90      .95 
##       56       57       59       60       61 
## 
## lowest : 43.0 44.0 49.0 50.0 50.1, highest: 71.0 73.0 76.0 79.0 95.0
## --------------------------------------------------------------------------------
## price 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##    53940        0    11602        1     3933     4012      544      646 
##      .25      .50      .75      .90      .95 
##      950     2401     5324     9821    13107 
## 
## lowest :   326   327   334   335   336, highest: 18803 18804 18806 18818 18823
## --------------------------------------------------------------------------------
## x 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##    53940        0      554        1    5.731    1.276     4.29     4.36 
##      .25      .50      .75      .90      .95 
##     4.71     5.70     6.54     7.31     7.66 
## 
## lowest :  0.00  3.73  3.74  3.76  3.77, highest: 10.01 10.02 10.14 10.23 10.74
## --------------------------------------------------------------------------------
## y 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##    53940        0      552        1    5.735    1.269     4.30     4.36 
##      .25      .50      .75      .90      .95 
##     4.72     5.71     6.54     7.30     7.65 
## 
## lowest :  0.00  3.68  3.71  3.72  3.73, highest: 10.10 10.16 10.54 31.80 58.90
##                                                                             
## Value        0.0   3.5   4.0   4.5   5.0   5.5   6.0   6.5   7.0   7.5   8.0
## Frequency      7     5  1731 12305  7817  5994  6742  9260  4298  3402  1635
## Proportion 0.000 0.000 0.032 0.228 0.145 0.111 0.125 0.172 0.080 0.063 0.030
##                                                     
## Value        8.5   9.0   9.5  10.0  10.5  32.0  59.0
## Frequency    652    69    14     6     1     1     1
## Proportion 0.012 0.001 0.000 0.000 0.000 0.000 0.000
## 
## For the frequency table, variable is rounded to the nearest 0.5
## --------------------------------------------------------------------------------
## z 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##    53940        0      375        1    3.539   0.7901     2.65     2.69 
##      .25      .50      .75      .90      .95 
##     2.91     3.53     4.04     4.52     4.73 
## 
## lowest :  0.00  1.07  1.41  1.53  2.06, highest:  6.43  6.72  6.98  8.06 31.80
##                                                                             
## Value        0.0   1.0   1.5   2.0   2.5   3.0   3.5   4.0   4.5   5.0   5.5
## Frequency     20     1     2     3  8807 13809  9474 13682  5525  2352   237
## Proportion 0.000 0.000 0.000 0.000 0.163 0.256 0.176 0.254 0.102 0.044 0.004
##                                         
## Value        6.0   6.5   7.0   8.0  32.0
## Frequency     20     5     1     1     1
## Proportion 0.000 0.000 0.000 0.000 0.000
## 
## For the frequency table, variable is rounded to the nearest 0.5
## --------------------------------------------------------------------------------</code></pre>
<p>Considering two outputs above, please answer the following
questions</p>
<div class="panel-heading tutorial-quiz-title"><span data-i18n="text.quiz">Quiz</span></div>
<div class="panel panel-default tutorial-question-container">
<div data-label="quiz2-1" class="tutorial-question panel-body">
<div id="quiz2-1-answer_container" class="shiny-html-output"></div>
<div id="quiz2-1-message_container" class="shiny-html-output"></div>
<div id="quiz2-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<pre><code>table1::table1(~ depth, data=diamonds)</code></pre>
<div class="Rtable1"><table class="Rtable1">
<thead>
<tr>
<th class='rowlabel firstrow lastrow'></th>
<th class='firstrow lastrow'><span class='stratlabel'>Overall<br><span class='stratn'>(N=53940)</span></span></th>
</tr>
</thead>
<tbody>
<tr>
<td class='rowlabel firstrow'>depth</td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel'>Mean (SD)</td>
<td>61.7 (1.43)</td>
</tr>
<tr>
<td class='rowlabel lastrow'>Median [Min, Max]</td>
<td class='lastrow'>61.8 [43.0, 79.0]</td>
</tr>
</tbody>
</table>
</div>
<p>For more alternatives, please <a
href="https://chrisdixonacademic.wordpress.com/2021/03/10/descriptive-statistics-in-r/">visit</a></p>
<p>You can also check <code>sumtable</code>package from <a
href="https://cran.r-project.org/web/packages/vtable/vignettes/sumtable.html">here</a></p>
<p><code>summary()</code> has no group-by function, but you can use
<code>psych</code> package to get some rudimentary statistics by
group:</p>
<pre><code>psych::describe(diamonds)</code></pre>
<p>This package also provides an opportunity that you can calculate
these summary statistics by breaking down a categorical variable.</p>
<pre><code>psych::describeBy(diamonds,diamonds$color)</code></pre>
<pre><code>## 
##  Descriptive statistics by group 
## group: D
##          vars    n    mean      sd  median trimmed     mad   min      max
## carat       1 6775    0.66    0.36    0.53    0.61    0.31   0.2     3.40
## cut*        2 6775    3.93    1.12    4.00    4.06    1.48   1.0     5.00
## color*      3 6775    1.00    0.00    1.00    1.00    0.00   1.0     1.00
## clarity*    4 6775    3.69    1.42    3.00    3.55    1.48   1.0     8.00
## depth       5 6775   61.70    1.41   61.80   61.74    1.19  52.2    71.60
## table       6 6775   57.40    2.21   57.00   57.26    1.48  52.0    73.00
## price       7 6775 3169.95 3356.59 1838.00 2457.57 1657.55 357.0 18693.00
## x           8 6775    5.42    0.94    5.23    5.34    1.10   0.0     9.42
## y           9 6775    5.42    0.94    5.24    5.35    1.10   0.0     9.34
## z          10 6775    3.34    0.58    3.22    3.30    0.68   0.0     6.27
##             range  skew kurtosis    se
## carat        3.20  1.29     2.04  0.00
## cut*         4.00 -0.70    -0.52  0.01
## color*       0.00   NaN      NaN  0.00
## clarity*     7.00  0.79     0.16  0.02
## depth       19.40 -0.26     2.56  0.02
## table       21.00  0.75     1.09  0.03
## price    18336.00  2.10     4.67 40.78
## x            9.42  0.56    -0.26  0.01
## y            9.34  0.55    -0.28  0.01
## z            6.27  0.55    -0.26  0.01
## ------------------------------------------------------------ 
## group: E
##          vars    n    mean      sd  median trimmed     mad    min      max
## carat       1 9797    0.66    0.37    0.53    0.61    0.31   0.20     3.05
## cut*        2 9797    3.89    1.10    4.00    4.02    1.48   1.00     5.00
## color*      3 9797    2.00    0.00    2.00    2.00    0.00   2.00     2.00
## clarity*    4 9797    3.97    1.56    4.00    3.85    1.48   1.00     8.00
## depth       5 9797   61.66    1.44   61.80   61.71    1.19  51.00    79.00
## table       6 9797   57.49    2.24   57.00   57.34    1.48  44.00    73.00
## price       7 9797 3076.75 3344.16 1739.00 2349.98 1537.46 326.00 18731.00
## x           8 9797    5.41    0.96    5.23    5.34    1.11   3.74     9.26
## y           9 9797    5.42    0.99    5.24    5.35    1.11   3.71    31.80
## z          10 9797    3.34    0.66    3.22    3.29    0.68   2.06    31.80
##             range  skew kurtosis    se
## carat        2.85  1.29     1.85  0.00
## cut*         4.00 -0.62    -0.59  0.01
## color*       0.00   NaN      NaN  0.00
## clarity*     7.00  0.55    -0.40  0.02
## depth       28.00  0.14     8.15  0.01
## table       29.00  0.71     1.27  0.02
## price    18405.00  2.17     4.89 33.79
## x            5.52  0.57    -0.39  0.01
## y           28.09  2.42    50.14  0.01
## z           29.74  8.60   352.76  0.01
## ------------------------------------------------------------ 
## group: F
##          vars    n    mean      sd  median trimmed     mad   min      max
## carat       1 9542    0.74    0.40    0.70    0.69    0.46   0.2     3.01
## cut*        2 9542    3.89    1.14    4.00    4.02    1.48   1.0     5.00
## color*      3 9542    3.00    0.00    3.00    3.00    0.00   3.0     3.00
## clarity*    4 9542    4.13    1.70    4.00    4.01    1.48   1.0     8.00
## depth       5 9542   61.69    1.44   61.80   61.73    1.04  52.3    71.00
## table       6 9542   57.43    2.26   57.00   57.28    1.48  50.0    95.00
## price       7 9542 3724.89 3784.99 2343.50 2974.69 2274.31 342.0 18791.00
## x           8 9542    5.61    1.01    5.65    5.57    1.25   0.0     9.24
## y           9 9542    5.62    1.00    5.65    5.57    1.25   0.0     9.13
## z          10 9542    3.46    0.63    3.48    3.43    0.77   0.0     5.73
##             range  skew kurtosis    se
## carat        2.81  0.99     0.90  0.00
## cut*         4.00 -0.70    -0.46  0.01
## color*       0.00   NaN      NaN  0.00
## clarity*     7.00  0.50    -0.53  0.02
## depth       18.70 -0.16     3.01  0.01
## table       45.00  1.30     9.83  0.02
## price    18449.00  1.75     2.82 38.75
## x            9.24  0.27    -0.45  0.01
## y            9.13  0.28    -0.55  0.01
## z            5.73  0.24    -0.38  0.01
## ------------------------------------------------------------ 
## group: G
##          vars     n    mean      sd  median trimmed     mad    min      max
## carat       1 11292    0.77    0.44    0.70    0.72    0.49   0.23     3.01
## cut*        2 11292    3.99    1.09    4.00    4.15    1.48   1.00     5.00
## color*      3 11292    4.00    0.00    4.00    4.00    0.00   4.00     4.00
## clarity*    4 11292    4.46    1.76    4.00    4.40    1.48   1.00     8.00
## depth       5 11292   61.76    1.37   61.80   61.78    1.04  43.00    72.90
## table       6 11292   57.29    2.15   57.00   57.16    1.48  52.00    76.00
## price       7 11292 3999.14 4051.10 2242.00 3245.61 2277.27 354.00 18818.00
## x           8 11292    5.68    1.08    5.64    5.61    1.36   0.00     9.44
## y           9 11292    5.68    1.08    5.63    5.62    1.35   0.00     9.37
## z          10 11292    3.51    0.67    3.48    3.47    0.85   0.00     6.16
##             range  skew kurtosis    se
## carat        2.78  0.96     0.57  0.00
## cut*         4.00 -0.85    -0.14  0.01
## color*       0.00   NaN      NaN  0.00
## clarity*     7.00  0.26    -0.74  0.02
## depth       29.90 -0.22     9.05  0.01
## table       24.00  0.75     1.45  0.02
## price    18464.00  1.50     1.72 38.12
## x            9.44  0.33    -0.78  0.01
## y            9.37  0.32    -0.79  0.01
## z            6.16  0.25    -0.44  0.01
## ------------------------------------------------------------ 
## group: H
##          vars    n    mean      sd  median trimmed     mad    min      max
## carat       1 8304    0.91    0.52    0.90    0.86    0.56   0.23     4.13
## cut*        2 8304    3.88    1.12    4.00    4.02    1.48   1.00     5.00
## color*      3 8304    5.00    0.00    5.00    5.00    0.00   5.00     5.00
## clarity*    4 8304    3.93    1.69    4.00    3.77    1.48   1.00     8.00
## depth       5 8304   61.84    1.44   61.90   61.86    1.04  52.70    71.80
## table       6 8304   57.52    2.24   57.00   57.39    1.48  50.00    73.00
## price       7 8304 4486.67 4215.94 3460.00 3755.13 3683.52 337.00 18803.00
## x           8 8304    5.98    1.20    6.14    5.94    1.36   0.00    10.00
## y           9 8304    5.98    1.32    6.14    5.94    1.35   0.00    58.90
## z          10 8304    3.70    0.74    3.82    3.67    0.86   0.00     8.06
##             range  skew kurtosis    se
## carat        3.90  0.79     0.34  0.01
## cut*         4.00 -0.75    -0.25  0.01
## color*       0.00   NaN      NaN  0.00
## clarity*     7.00  0.67    -0.29  0.02
## depth       19.10  0.16     3.71  0.02
## table       23.00  0.66     1.17  0.02
## price    18466.00  1.38     1.45 46.26
## x           10.00  0.07    -0.82  0.01
## y           58.90  7.80   309.80  0.01
## z            8.06  0.05    -0.42  0.01
## ------------------------------------------------------------ 
## group: I
##          vars    n    mean      sd  median trimmed     mad    min      max
## carat       1 5422    1.03    0.58    1.00    0.98    0.73   0.23     4.01
## cut*        2 5422    3.87    1.13    4.00    4.01    1.48   1.00     5.00
## color*      3 5422    6.00    0.00    6.00    6.00    0.00   6.00     6.00
## clarity*    4 5422    3.96    1.60    4.00    3.83    1.48   1.00     8.00
## depth       5 5422   61.85    1.46   61.90   61.88    1.04  50.80    71.30
## table       6 5422   57.58    2.30   57.00   57.46    1.48  43.00    70.00
## price       7 5422 5091.87 4722.39 3730.00 4332.86 4067.51 334.00 18823.00
## x           8 5422    6.22    1.25    6.35    6.20    1.47   3.94    10.14
## y           9 5422    6.22    1.24    6.35    6.20    1.45   3.90    10.10
## z          10 5422    3.85    0.77    3.93    3.83    0.92   0.00     6.31
##             range  skew kurtosis    se
## carat        3.78  0.64    -0.15  0.01
## cut*         4.00 -0.70    -0.42  0.02
## color*       0.00   NaN      NaN  0.00
## clarity*     7.00  0.59    -0.23  0.02
## depth       20.50 -0.03     3.80  0.02
## table       27.00  0.57     1.21  0.03
## price    18489.00  1.16     0.42 64.13
## x            6.20  0.02    -1.00  0.02
## y            6.20  0.01    -1.00  0.02
## z            6.31 -0.02    -0.88  0.01
## ------------------------------------------------------------ 
## group: J
##          vars    n    mean      sd  median trimmed     mad    min      max
## carat       1 2808    1.16    0.60    1.11    1.13    0.61   0.23     5.01
## cut*        2 2808    3.73    1.14    4.00    3.84    1.48   1.00     5.00
## color*      3 2808    7.00    0.00    7.00    7.00    0.00   7.00     7.00
## clarity*    4 2808    3.78    1.40    4.00    3.68    1.48   1.00     8.00
## depth       5 2808   61.89    1.55   62.00   61.93    1.04  43.00    73.60
## table       6 2808   57.81    2.31   58.00   57.73    2.97  51.60    68.00
## price       7 2808 5323.82 4438.19 4234.00 4721.87 4088.27 335.00 18710.00
## x           8 2808    6.52    1.20    6.64    6.54    1.25   3.93    10.74
## y           9 2808    6.52    1.20    6.63    6.54    1.25   3.90    10.54
## z          10 2808    4.03    0.74    4.11    4.05    0.79   2.46     6.98
##             range  skew kurtosis    se
## carat        4.78  0.61     0.51  0.01
## cut*         4.00 -0.58    -0.52  0.02
## color*       0.00   NaN      NaN  0.00
## clarity*     7.00  0.60     0.37  0.03
## depth       30.60 -0.50    10.91  0.03
## table       16.40  0.46     0.54  0.04
## price    18375.00  1.03     0.28 83.75
## x            6.81 -0.15    -0.73  0.02
## y            6.64 -0.15    -0.75  0.02
## z            4.52 -0.13    -0.69  0.01</code></pre>
<p>As you see, we can calculate each of summary statistics of the
numerical variables by color type.</p>
<p>If you would like to calculate the descriptive statistics of a single
numerical variable by a group, you can use <code>aggregate()</code>
command.</p>
<p><strong>Research Question 1</strong></p>
<p>What is the average depth of diamonds in the premium cut class
compared to other classes within more than 50000 diamonds?</p>
<p><strong>Question: What is type of EDA and why it is called in that
way?</strong></p>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["cut"],"name":[1],"type":["ord"],"align":["right"]},{"label":["depth"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"Fair","2":"64.04168"},{"1":"Good","2":"62.36588"},{"1":"Very Good","2":"61.81828"},{"1":"Premium","2":"61.26467"},{"1":"Ideal","2":"61.70940"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p><span style="color:darkred">Interpretation</span></p>
<p>The average depth of premium cut diamond is 61.26. The table shows
that the average depth of diamonds by their cut are close to each other,
but the average depth of fair cut diamonds, which is 64.04, are slightly
above the others on the average.</p>
<div id="section-univariate-eda" class="section level4">
<h4><span style="color:darkred"><strong>Univariate
EDA</strong></span></h4>
</div>
<div id="section-categorical-variables" class="section level4">
<h4><span style="color:darkred"><strong>Categorical
Variables</strong></span></h4>
<p><span style="color:darkred"><strong>Frequency
Table:</strong></span>Frequency refers to the number of times an event
or a value occurs. A frequency table is a table that lists items and
shows the number of times the items occur. It is generally applied on
categorical variables.</p>
<pre><code>table(diamonds$cut) #creates frequency table </code></pre>
<pre><code>## 
##      Fair      Good Very Good   Premium     Ideal 
##      1610      4906     12082     13791     21551</code></pre>
<p>Interpretation is above.</p>
<pre><code>prop.table(table(diamonds$cut)) #shows proportions</code></pre>
<pre><code>## 
##       Fair       Good  Very Good    Premium      Ideal 
## 0.02984798 0.09095291 0.22398962 0.25567297 0.39953652</code></pre>
<p><span style="color:darkred">Interpretation</span></p>
<p>The proportion of diamonds by their cut type indicates the
distribution of diamonds across different cut categories.</p>
<p>Fair cut diamonds represent 2.98% of the total diamonds in the
dataset. Good cut diamonds represent 9.10% of the total diamonds in the
dataset. Very Good cut diamonds represent 22.40% of the total diamonds
in the dataset. Premium cut diamonds represent 25.57% of the total
diamonds in the dataset. Ideal cut diamonds represent 39.95% of the
total diamonds in the dataset.</p>
<p>These proportions can be used to gain insights into the quality of
diamonds in the dataset. For example, the relatively high proportion of
premium and ideal cut diamonds suggests that the overall quality of
diamonds in the dataset may be high, while the relatively low proportion
of fair cut diamonds may suggest that the dataset contains fewer lower
quality diamonds.</p>
<p><span style="color:darkred"><strong>Bar Plot:</strong></span> A bar
chart represents data in rectangular bars with length of the bar
proportional to the value of the variable. It is used for the
visualization of the categorical variable, i.e displaying the
distribution of categorical variable.</p>
<p>To create bar plot in R, you need to create the frequency table of
the categorical variable at first.</p>
<p><strong>Research Question 2</strong></p>
<p>What is the frequency distribution of CUT?</p>
<pre><code>c = table(diamonds$cut)
barplot(c)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-17-1.png" width="624" /></p>
<pre><code>barplot(c,col=c(&quot;red&quot;,&quot;yellow&quot;,&quot;black&quot;,&quot;blue&quot;,&quot;orange&quot;),main=&quot;Bar Plot of Cut&quot;)
text(c,labels=c,col=&quot;white&quot;,pos=1)
# col argument fills the bar
# main argument adds title
#ylim argument arranges the y-axis
#names.arg argument changes the bar names
#text argument shows the frequencies on the plot.  
#chas is the name of the frequency table</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-18-1.png" width="624" /></p>
<p><strong>Note:</strong> Bar plots are sometimes are used in the
illustration of numerical variable.</p>
</div>
<div id="section-numerical-variables" class="section level4">
<h4><span style="color:darkred"><strong>Numerical
Variables</strong></span></h4>
<p>As a numerical EDA, the summary statistics including mean, median,
standard deviation etc. are considered. You can find how to do in R
above.</p>
<p><span style="color:darkred"><strong>Histogram:</strong></span> A
histogram represents the frequencies of values of a variable bucketed
into ranges. Histogram is similar to bar chat but the difference is it
groups the values into continuous ranges. Each bar in histogram
represents the height of the number of values present in that range.</p>
<p><strong>Research Question 3</strong></p>
<p>What is the distribution of carat?</p>
<pre><code>hist(diamonds$carat) #hist function is used to draw histogram</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-19-1.png" width="624" /></p>
<pre><code>hist(diamonds$carat,col=&quot;red&quot;,main=&quot;Histogram of Carat&quot;,xlab=&quot;Frequency of Carat&quot;)
#xlab changes the x axis name. </code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-20-1.png" width="624" /></p>
<p><strong>Same Histogram with different bin</strong></p>
<p><strong>Bin:</strong> The bar in the histogram is called bin.</p>
<pre><code>hist(diamonds$carat,col=&quot;red&quot;,main=&quot;Histogram of Carat&quot;,xlab=&quot;Frequency of Carat&quot;,breaks = 20)
#xlab changes the x axis name. 
#breaks sets the number of bin in the histogram</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-21-1.png" width="624" /></p>
<p>Let’s make it more informative by adding the central tendency
measures to the histogram.</p>
<pre><code>hist(diamonds$carat,col=&quot;darkred&quot;,main=&quot;Histogram of Carat&quot;,xlab=&quot;Frequency of Carat&quot;,breaks = 20)
abline(v = mean(diamonds$carat),col = &quot;royalblue&quot;, lwd = 2) #abbline add the vertical or horizontal line
abline(v = median(diamonds$carat),col = &quot;orange&quot;,lwd = 2)
legend(x = &quot;topright&quot;, # location of legend within plot area
 c(&quot;Mean&quot;, &quot;Median&quot;),
 col = c(&quot;royalblue&quot;, &quot;orange&quot;),
 lwd = c(2, 2, 2))</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-22-1.png" width="624" /></p>
<p>The carat of diamonds has a multimodal and right skewed distribution.
The average and median of carats are close to each other, and they show
that the center of the carat of the diamonds is less than 1. The
histogram shows that carat of the most of the diamonds are between 0-1
carat. The diamond database has a few number of valuable diamonds in
terms of carat.</p>
<p><span style="color:darkred"><strong>Density Plot:</strong></span> A
density plot is a representation of the distribution of a numeric
variable. It uses a kernel density estimate to show the probability
density function of the variable <a
href="https://chemicalstatistician.wordpress.com/2013/06/09/exploratory-data-analysis-kernel-density-estimation-in-r-on-ozone-pollution-data-in-new-york-and-ozonopolis/">see
more</a>. It is <strong>a smoothed version</strong> of the histogram and
is used in the same concept.</p>
<pre><code>d = density(diamonds$carat)
print(d)
#Bandwidth is a parameter used for arranging the degree of smoothness.</code></pre>
<pre><code>## 
## Call:
##  density.default(x = diamonds$carat)
## 
## Data: diamonds$carat (53940 obs.);   Bandwidth &#39;bw&#39; = 0.04827
## 
##        x                y            
##  Min.   :0.0552   Min.   :0.0000000  
##  1st Qu.:1.3301   1st Qu.:0.0001509  
##  Median :2.6050   Median :0.0037733  
##  Mean   :2.6050   Mean   :0.1959014  
##  3rd Qu.:3.8799   3rd Qu.:0.1916445  
##  Max.   :5.1548   Max.   :1.7672776</code></pre>
<pre><code>plot(d,col=&quot;red&quot;,main=&quot;Density Plot of Carat&quot;,type=&quot;l&quot;)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-24-1.png" width="624" /></p>
<p><span style="color:darkred">Interpretation</span></p>
<p>It has a <strong>multimodal</strong> and <strong>right</strong>
distribution.</p>
<p><strong>Histogram with density plot</strong></p>
<p>If you would like to draw a histogram with density plot, you should
use <code>prob=T</code> argument.</p>
<pre><code>hist(diamonds$carat,col=&quot;red&quot;,main=&quot;Histogram of Carat&quot;,xlab=&quot;Frequency of Carat&quot;,breaks = 20,prob=T)
lines(density(diamonds$carat),col=&quot;blue&quot;,main=&quot;Density Plot of Carat&quot;,type=&quot;l&quot;)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-25-1.png" width="624" /></p>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-26-1.png" width="624" /></p>
<div class="panel-heading tutorial-quiz-title"><span data-i18n="text.quiz">Quiz</span></div>
<div class="panel panel-default tutorial-question-container">
<div data-label="quiz3-1" class="tutorial-question panel-body">
<div id="quiz3-1-answer_container" class="shiny-html-output"></div>
<div id="quiz3-1-message_container" class="shiny-html-output"></div>
<div id="quiz3-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<p><span style="color:darkred"><strong>Box and Whiskers
Plot:</strong></span> It is created based on Tukeys Five Number Summary
including minimum, maximum, median, first and third quartile. The box
plot can be used for two main purposes,</p>
<ul>
<li><p>To investigate the distribution of a univariate numerical
variable and checking <strong>the existence of outliers</strong>.
However, it is not a good idea for characterizing the distribution
because it cannot visualize the peak points of the distribuion.</p></li>
<li><p>To see the relationship between numerical variable and
categorical variable with levels or compare a numerical variable with
respect to a categorical variable.</p></li>
</ul>
<p>Therefore, it is suitable for both univariate and multivariate
EDA.</p>
<p><strong>Anatomy of Box Plot</strong></p>
<div class="figure">
<img
src="https://miro.medium.com/max/18000/1*2c21SkzJMf3frPXPAR_gZA.png"
style="width:80.0%" alt="" />
<p class="caption">Anatomy of Box Plot</p>
</div>
<p><strong>Research Question 3</strong></p>
<p>Within more than 53000 diamonds, are diamonds with extremely valuable
or unvaluable available?</p>
<pre><code>boxplot(diamonds$carat)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-27-1.png" width="624" /></p>
<pre><code>boxplot(diamonds$carat,main=&quot;Box Plot of Carat&quot;,xlab=&quot;Carat&quot;,col=&quot;red&quot;)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-28-1.png" width="624" /></p>
<p><span style="color:darkred">Interpretation:</span> The half of the
carat of the diamonds is around 0.5. The variation in middle half of the
carat of the diamond is not high. There are some precious diamonds based
on their carat.</p>
<p>When your variable has outliers, you can use <strong>median</strong>
as central of tendency measure, and <strong>IQR</strong> as the measure
of variation.</p>
<p><strong>Box Plot on the top of the Histogram</strong></p>
<pre><code># Draw the boxplot and the histogram 
layout(mat = matrix(c(1,2),2,1, byrow=TRUE),  height = c(1,8))
par(mar=c(0, 3.1, 1.1, 2.1))
boxplot(diamonds$carat,main=&quot;Box Plot and Histogram of Carat &quot;,col=&quot;red&quot;,horizontal=TRUE,frame=F)
par(mar=c(1, 3.1, 1.1, 2.1))
hist(diamonds$carat,col=&quot;red&quot;,xlab=&quot;Carat&quot;,main=&quot;&quot;)
#xlab changes the x axis name. </code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-29-1.png" width="624" /></p>
<p><span style="color::darkred"> <strong>Mid-Exercise 1</strong>
</span></p>
<p><strong>What is the variation of Price?</strong></p>
<p>Type a R code to draw a histogram and density plot. Explain what you
get.</p>
</div>
<div id="section-multivariate-eda" class="section level3">
<h3><span style="color:darkred"><strong>Multivariate
EDA</strong></span></h3>
<p>In order to do Multivariate EDA, we need to take more than one
variable into the analysis.</p>
<div id="section-categorical-variables-1" class="section level4">
<h4><span style="color:darkred"><strong>Categorical
Variables</strong></span></h4>
<p><strong>Research Question 4</strong></p>
<p>How does the color of diamonds changes over cut type among 53940
diamonds?</p>
<p>If you are analyzing two categorical variables, we can still create a
frequency table, called <strong>contingency table.</strong></p>
<p><strong>Contingency Table :</strong> In statistics, a contingency
table, also known as a cross tabulation or crosstab, is a type of table
in a matrix format that displays the multivariate frequency distribution
of the variables. They are heavily used in survey research, business
intelligence, engineering and scientific research. -Vikipedia :)</p>
<p>You can create contingency table by using <code>table()</code> in
R.</p>
<pre><code>table(diamonds$color,diamonds$cut)</code></pre>
<pre><code>##    
##     Fair Good Very Good Premium Ideal
##   D  163  662      1513    1603  2834
##   E  224  933      2400    2337  3903
##   F  312  909      2164    2331  3826
##   G  314  871      2299    2924  4884
##   H  303  702      1824    2360  3115
##   I  175  522      1204    1428  2093
##   J  119  307       678     808   896</code></pre>
<p>You can display the contingency table in different formats.</p>
<p><span style="color:darkred">Mosaic Plot:</span> A mosaic plot is a
graphical display of the cell frequencies of a contingency table in
which the area of boxes of the plot are proportional to the cell
frequencies of the contingency table. This procedure can construct
mosaic plots for up to four-way tables.</p>
<pre><code>mosaicplot(~diamonds$color+diamonds$cut)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-31-1.png" width="624" /></p>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-32-1.png" width="624" /></p>
<p><span style="color:darkred">Interpretation</span></p>
<p>We can say that the mostly occurring color between ideal cut diamonds
is G color. This example also indicates the weakness of mosaic plot. The
interpretation is harder when we have more than 3 levels for each
variable.</p>
<p><span style="color:darkred">Grouped Bar Plot:</span> It is an
efficient tool to display the association between two categorical
variables.</p>
<pre><code>counts = table(diamonds$color,diamonds$cut)
barplot(counts, main=&quot;Color Distribution by Cut Type&quot;,
  xlab=&quot;Median value of Income&quot;, col=c(&quot;grey&quot;,&quot;darkred&quot;,&quot;orange&quot;,&quot;black&quot;,&quot;maroon&quot;,&quot;gold1&quot;,&quot;darkgreen&quot;),
  legend = rownames(counts),beside=TRUE)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-33-1.png" width="624" /></p>
<p><span style="color:darkred">Interpretation</span></p>
<p>It can be said that the frequency of color J increases as the quality
of diamond cut increases. Also, the plot shows that most of the diamonds
have color G.</p>
<p>What else?</p>
<p><span style="color:darkred">Stacked Bar Plot:</span> A stacked
barplot is very similar to the grouped barplot above. The subgroups are
just displayed on top of each other, not beside. The stacked barchart is
the default option of the <code>barplot()</code> function in base R, so
you do not need to use the beside argument.</p>
<pre><code>counts = table(diamonds$color,diamonds$cut)
barplot(counts, main=&quot;Color Distribution by Cut Type&quot;,
  xlab=&quot;Cut Type&quot;, col=colors()[c(22,32,42,52,62,72,82)],
  legend = rownames(counts))</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-34-1.png" width="624" /></p>
<p>The interpretation is in the previous plot.</p>
</div>
<div id="section-continuous-variables" class="section level4">
<h4><span style="color:darkred"><strong>Continuous
Variables</strong></span></h4>
<p><strong>Research Question 5</strong></p>
<p>What is the association between carat and price within 53940 diamonds
having different properties?</p>
<p><span style="color:darkred">Scatter Plot: </span> Scatter plot is a
graphical way used to display the relationship between two numeric
variables by using dots. Each dot represents an observation. Their
position on the X (horizontal) and Y (vertical) axis represents the
values of the 2 variables.</p>
<pre><code>plot(diamonds$carat,diamonds$price)
#logic-&gt; plot(independent variable, dependent variable)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-35-1.png" width="624" /></p>
<pre><code>plot(diamonds$carat,diamonds$price,main=&quot;The Association btw Carat and Price&quot;,xlab=&quot;Carat&quot;,ylab=&quot;Price&quot;,col=&quot;darkred&quot;,pch=12,cex=1)
#cex=size of dots
#pch=point type</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-36-1.png" width="624" /></p>
<p>The plot indicates the positive association between two attributes.
It is seen that when the carat increases, the prices increases. However,
it is also seen that there are some observations, which can be labelled
as outlier, that distords the relationship.</p>
<p><strong>Scatter Plot with Polynomial Curve</strong></p>
<pre><code>plot(diamonds$carat,diamonds$price,main=&quot;The Association btw Carat and Price&quot;,xlab=&quot;Carat&quot;,ylab=&quot;Price&quot;,col=rgb(0.4,0.4,0.8,0.6),pch=16,cex=1,ylim=c(-3500,17000))
model &lt;- lm(diamonds$price~diamonds$carat)
 
# I can get the features of this model :
#summary(model)
#model$coefficients
#summary(model)$adj.r.squared
 
# For each value of x, I can get the value of y estimated by the model, and add it to the current plot !
myPredict &lt;- predict( model ) 
ix &lt;- sort(diamonds$carat,index.return=T)$ix
lines(diamonds$carat[ix], myPredict[ix], col=2, lwd=0.5 )  

# I add the features of the model to the plot
coeff &lt;- round(model$coefficients , 2)
text(3, -2000 , paste(&quot;Model : &quot;,coeff[1] , &quot; + &quot; , coeff[2] , &quot;*x&quot;  , &quot;\n\n&quot; , &quot;P-value adjusted = &quot;,round(summary(model)$adj.r.squared,2)))</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-37-1.png" width="624" /></p>
<p>You can customize your scatter plot using the following arguments in
the plot function.</p>
<ul>
<li><p>cex = shape size</p></li>
<li><p>lwd = line width</p></li>
<li><p>col = control colors</p></li>
<li><p>lty = line type</p></li>
<li><p>pch = marker shape</p></li>
<li><p>type = link between dots</p></li>
</ul>
</div>
<div id="section-categorical-and-numerical-variables"
class="section level4">
<h4><span style="color:darkred"><strong>Categorical and Numerical
Variables</strong></span></h4>
<p><strong>Research Question 6</strong></p>
<p>How cut types of the diamonds affected the prices for 53940
diamonds?</p>
<p><span style="color:darkred">Box and Whisker Plot</span> It is
probably the most commonly used chart type to compare distribution of
several groups.</p>
<pre><code>boxplot(diamonds$price~diamonds$cut,main=&quot;The Boxplot of Diamond Prices by Cut&quot;,col=colors()[c(25,35,45,55,65)],xlab=&quot;Cut Type&quot;,ylab=&quot;Price&quot;,ylim=c(0,25000))

legend(&quot;topleft&quot;, legend = levels(diamonds$cut) , 
    col=colors()[c(25,35,45,55,65)] , bty = &quot;n&quot;, pch=20 , pt.cex = 1, cex = 1, horiz = T, inset = c(0.01, 0.01))
#inset set the position of legend
#horiz = add legend horizontally</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-38-1.png" width="624" /></p>
<p><span style="color:darkred">Interpretation</span></p>
<p>The median prices for each cut type are close to each other, but
upper tail of whiskers indices that the price of premium cut diamonds is
the highest among them and it reduces as quality of cut type reduces.
Thus, a visual association is detected, but it requires further
analysis. On the other hand, all of them have outlier observations and
might have right skewed distribution but more visual technique should be
considered.</p>
<p><span style="color::darkred"> <strong>Mid-Exercise 2</strong>
</span></p>
<p><strong>How diamonds prices distribute over color type?</strong></p>
<p><strong>Research Question 7</strong></p>
<p>How diamonds prices distribute over cut type and depth?</p>
<p>Here, we need a transformation because we aim to analze a numerical
variable(price) by two categorical variables(cut and depth).</p>
<pre><code>diamonds$depth_factor = ifelse(diamonds$depth&lt;mean(diamonds$depth),&quot;Below Average&quot;,&quot;Above Average&quot;)</code></pre>
<pre><code># I make the boxplot, asking to use the 2 factors : depth factor and cut:
par(mar=c(3,4,3,1))
myplot &lt;-
boxplot(price ~ depth_factor*cut , data=diamonds,
        boxwex=0.4 , ylab=&quot;Price&quot;,
        main=&quot;The Box Plot of Price by Cut and Depth&quot; , 
        col=c(&quot;slateblue1&quot; , &quot;tomato&quot;) ,  
        xaxt=&quot;n&quot;,ylim=c(0,30000))

my_names &lt;- sapply(strsplit(myplot$names , &#39;\\.&#39;) , function(x) x[[2]] )
my_names &lt;- my_names[seq(1 , length(my_names) , 2)]

axis(1, at =seq(0.5 , 10 , 2),labels = my_names , 
     tick=FALSE , cex=0.3)

# Add the grey vertical lines
for(i in seq(0.5 ,10 , 2)){ 
  abline(v=i,lty=1, col=&quot;grey&quot;)
  }
 

# Add a legend
legend(&quot;topright&quot;, legend = c(&quot;Above&quot;, &quot;Below&quot;), 
       col=c(&quot;slateblue1&quot; , &quot;tomato&quot;),
       pch = 15, bty = &quot;n&quot;, pt.cex = 3, cex = 1.2,  horiz = F, inset = c(0.1, 0.1))

</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-40-1.png" width="624" /></p>
<p><span style="color:darkred">Interpretation</span></p>
<p>The price of diamonds does not show a visual difference by their
depth for each cut type.</p>
<p><strong>Research Question 8</strong></p>
<p>How the carat of the diamonds related with the price of 539400
diamonds?</p>
<p>We are looking for the relationship between two quantitative
behaviour. The fastest way to do is either drawing scatter plot or
calculating correlation.</p>
<p>While answering this question, we will also check the association
between other quantitative variables simultaneously.</p>
<p><span style="color:darkred"><strong>Scatter Plot
Matrix:</strong></span> The graphical distribution of the data displays
the story of the data by spending less cognitive effort. If your dataset
has more than 2 quantitative variables, you can construct a scatter plot
matrix to understand the underlying relationship between them instead of
drawing a scatter plot for each pair of the variables one by one.</p>
<p>In this analysis, we need to include only numerical columns. Thus, we
will create an index which selects only numerical variables.</p>
<pre><code>index&lt;- unlist(lapply(diamonds, is.numeric))  </code></pre>
<pre><code>pairs(diamonds[,index])</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-42-1.png" width="624" /></p>
<p>Let’s make it more informative.</p>
<pre><code>library(PerformanceAnalytics)
chart.Correlation(diamonds[,index])</code></pre>
<pre><code>## Warning: package &#39;PerformanceAnalytics&#39; was built under R version 4.1.1</code></pre>
<pre><code>## Zorunlu paket yükleniyor: xts</code></pre>
<pre><code>## Warning: package &#39;xts&#39; was built under R version 4.1.3</code></pre>
<pre><code>## Zorunlu paket yükleniyor: zoo</code></pre>
<pre><code>## Warning: package &#39;zoo&#39; was built under R version 4.1.3</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre><code>## 
## ################################### WARNING ###################################
## # We noticed you have dplyr installed. The dplyr lag() function breaks how    #
## # base R&#39;s lag() function is supposed to work, which breaks lag(my_xts).      #
## #                                                                             #
## # If you call library(dplyr) later in this session, then calls to lag(my_xts) #
## # that you enter or source() into this session won&#39;t work correctly.          #
## #                                                                             #
## # All package code is unaffected because it is protected by the R namespace   #
## # mechanism.                                                                  #
## #                                                                             #
## # Set `options(xts.warn_dplyr_breaks_lag = FALSE)` to suppress this warning.  #
## #                                                                             #
## # You can use stats::lag() to make sure you&#39;re not using dplyr::lag(), or you #
## # can add conflictRules(&#39;dplyr&#39;, exclude = &#39;lag&#39;) to your .Rprofile to stop   #
## # dplyr from breaking base R&#39;s lag() function.                                #
## ################################### WARNING ###################################</code></pre>
<pre><code>## 
## Attaching package: &#39;PerformanceAnalytics&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:graphics&#39;:
## 
##     legend</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-43-1.png" width="624" /></p>
<p><span style="color:darkred"> Interpretation </span></p>
<p>The output shows that there is a strong linear association between
carat and price of the 53940 diamonds. It also shows the association
between pairs of the variables in both numerically and visually.</p>
<p>As you know, R has many number of packages for visualization,
<strong>better than Python.</strong> We will cover some of those in this
lab.</p>
</div>
<div id="section-lattice-plots" class="section level4">
<h4><span style="color:darkred"><strong>Lattice
Plots</strong></span></h4>
<p>It is a powerful and elegant high-level data visualization system,
with an emphasis on multivariate data. <strong>It generates a plot
splitted into the level of a categorical variable. </strong></p>
<p>What it has?</p>
<p><img
src="https://techvidvan.com/tutorials/wp-content/uploads/sites/2/2020/05/Graphs-in-Lattice-Package.jpg"
style="width:50.0%" /></p>
<p><strong>Research Question 9</strong></p>
<p>How the cut type affected the association between price and carats of
539400 diamonds?</p>
<p><span style="color:darkred">Scatter Plot in Lattice</span>
<code>lattice</code> library offers the <code>xyplot()</code> function.
It builds a scatterplot for each levels of a factor automatically.</p>
<pre><code>library(lattice)
xyplot(price ~ carat | cut , data=diamonds , pch=20 , cex=0.5 , col=rgb(0.2,0.4,0.8,0.5) )</code></pre>
<pre><code>## Warning: package &#39;lattice&#39; was built under R version 4.1.2</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-44-1.png" width="624" /></p>
<p><span style="color:darkred"> Interpretation </span> Carat and price
have positive relationship in each cut type as we expected. However, it
is also noted that some independent observations that brokes the
relationship exist.</p>
<p>You can also make your scatter plot colorful by the level of one
factor variable using <code>xyplot()</code>.</p>
<pre><code>xyplot(price ~ carat , data=diamonds,group = cut,auto.key = TRUE)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-45-1.png" width="624" /></p>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-46-1.png" width="624" /></p>
<div class="panel-heading tutorial-quiz-title"><span data-i18n="text.quiz">Quiz</span></div>
<div class="panel panel-default tutorial-question-container">
<div data-label="quiz44-1" class="tutorial-question panel-body">
<div id="quiz44-1-answer_container" class="shiny-html-output"></div>
<div id="quiz44-1-message_container" class="shiny-html-output"></div>
<div id="quiz44-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<p><strong>Research Question 10?</strong></p>
<p>How does the price of diamonds distribute by color of diamonds?</p>
<p>There are several ways to answer this question, and see the possible
solutions below.</p>
<p><span style="color:darkred">Histogram</span></p>
<pre><code>histogram(~ price | color, data = diamonds, breaks = 20)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-47-1.png" width="624" /></p>
<p><span style="color:darkred"> Interpretation </span> We can say that
price has multimodal distribution for color H, I and J and right skewed
distribution for the rest of the colors.</p>
<p><span style="color:darkred">Density Plot</span></p>
<pre><code>densityplot(~ price | color, data = diamonds)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-48-1.png" width="624" /></p>
<pre><code>densityplot(~price ,group=color, data = diamonds,auto.key = TRUE)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-49-1.png" width="624" /></p>
<p><span style="color:darkred">Box and Violin Plot</span></p>
<pre><code>bwplot(~ price | color, data = diamonds)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-50-1.png" width="624" /></p>
<p><span style="color:darkred"><strong>Violin Plot:</strong></span>
Violin plots are similar to box plots, except that they also show the
kernel probability density of the data at different values.</p>
<pre><code>bwplot(~ price | color, data = diamonds,panel = panel.violin)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-51-1.png" width="624" /></p>
<p><strong>Recall Research Question 6</strong></p>
<pre><code>bwplot(price ~  cut, data = diamonds)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-52-1.png" width="624" /></p>
<p><strong>Recall Research Question 4</strong></p>
<p><span style="color:darkred"> Heat Map</span></p>
<pre><code>df&lt;-table(diamonds$color,diamonds$cut)
levelplot(df)</code></pre>
<p><img src="Recitation1_files/figure-html/unnamed-chunk-53-1.png" width="624" /></p>
</div>
</div>
<div id="section-exercise" class="section level3">
<h3>Exercise</h3>
<p><span style="color:red"> <strong>Mid-Exercise 1</strong></span></p>
<p><strong>How the cut type affected the association between price and
carats of 539400 diamonds?</strong></p>
<p>Please click <a
href="http://users.metu.edu.tr/ozancan/exercise1.zip">here</a> to
download your exercise.</p>
<p><strong>References</strong></p>
<ul>
<li><p><a
href="https://r4ds.had.co.nz/exploratory-data-analysis.html#covariation"
class="uri">https://r4ds.had.co.nz/exploratory-data-analysis.html#covariation</a></p></li>
<li><p><a href="https://www.r-graph-gallery.com/"
class="uri">https://www.r-graph-gallery.com/</a></p></li>
<li><p><a
href="https://www.guide2research.com/research/how-to-write-a-research-question"
class="uri">https://www.guide2research.com/research/how-to-write-a-research-question</a></p></li>
</ul>
<p>
<script type="application/shiny-prerendered" data-context="server-start">
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>


<script type="application/shiny-prerendered" data-context="server">
learnr:::prepare_tutorial_state(session)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::i18n_observe_tutorial_language(input, session)
</script>


<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::event_trigger(session, "session_stop")
      })
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz1-1", question = structure("Which question is a good research question to investigate?", html = TRUE, class = c("html", 
"character")), answers = list(structure(list(id = "lnr_ans_6993a60", 
    option = "Has there been an increase in childhood obesity in the US in the past 10 years?", 
    value = "Has there been an increase in childhood obesity in the US in the past 10 years?", 
    label = structure("Has there been an increase in childhood obesity in the US in the past 10 years?", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL, type = "literal"), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_52fd4a4", 
    option = "How have school intervention programs and parental education levels affected the rate of childhood obesity among 1st to 6th-grade students?", 
    value = "How have school intervention programs and parental education levels affected the rate of childhood obesity among 1st to 6th-grade students?", 
    label = structure("How have school intervention programs and parental education levels affected the rate of childhood obesity among 1st to 6th-grade students?", html = TRUE, class = c("html", 
    "character")), correct = TRUE, message = NULL, type = "literal"), class = c("tutorial_question_answer", 
"tutorial_quiz_answer"))), button_labels = list(submit = structure("<span data-i18n=\"button.questionsubmit\">Submit Answer<\u002fspan>", html = TRUE, class = c("html", 
"character")), try_again = structure("<span data-i18n=\"button.questiontryagain\">Try Again<\u002fspan>", html = TRUE, class = c("html", 
"character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", 
"character")), try_again = structure("Incorrect", html = TRUE, class = c("html", 
"character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", 
"character")), message = NULL, post_message = NULL), ids = list(
    answer = "quiz1-1-answer", question = "quiz1-1"), loading = NULL, 
    random_answer_order = FALSE, allow_retry = FALSE, seed = 26095984.9878481, 
    options = list()), class = c("learnr_radio", "tutorial_question"
)), session = session)
</script>


<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz2-1", question = structure("Which one of the following is True?", html = TRUE, class = c("html", 
"character")), answers = list(structure(list(id = "lnr_ans_97b017f", 
    option = "The spread of x and y around their mean are not close to each other. ", 
    value = "The spread of x and y around their mean are not close to each other. ", 
    label = structure("The spread of x and y around their mean are not close to each other.", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL, type = "literal"), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_b01de51", 
    option = "Mean and median of depth are not close to each other.", 
    value = "Mean and median of depth are not close to each other.", 
    label = structure("Mean and median of depth are not close to each other.", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL, type = "literal"), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_425330a", 
    option = "3% percentage of the diamonds are best in terms of cleaning.", 
    value = "3% percentage of the diamonds are best in terms of cleaning.", 
    label = structure("3% percentage of the diamonds are best in terms of cleaning.", html = TRUE, class = c("html", 
    "character")), correct = TRUE, message = NULL, type = "literal"), class = c("tutorial_question_answer", 
"tutorial_quiz_answer"))), button_labels = list(submit = structure("<span data-i18n=\"button.questionsubmit\">Submit Answer<\u002fspan>", html = TRUE, class = c("html", 
"character")), try_again = structure("<span data-i18n=\"button.questiontryagain\">Try Again<\u002fspan>", html = TRUE, class = c("html", 
"character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", 
"character")), try_again = structure("Incorrect", html = TRUE, class = c("html", 
"character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", 
"character")), message = NULL, post_message = NULL), ids = list(
    answer = "quiz2-1-answer", question = "quiz2-1"), loading = NULL, 
    random_answer_order = FALSE, allow_retry = FALSE, seed = 228008745.393825, 
    options = list()), class = c("learnr_radio", "tutorial_question"
)), session = session)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz3-1", question = structure("How does the diamonds length distribute across 53894 diamonds?", html = TRUE, class = c("html", 
"character")), answers = list(structure(list(id = "lnr_ans_8439d6f", 
    option = "Multimodal-Symmetric", value = "Multimodal-Symmetric", 
    label = structure("Multimodal-Symmetric", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL, type = "literal"), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_36e5c3b", 
    option = "Multimodal-Right Skewed", value = "Multimodal-Right Skewed", 
    label = structure("Multimodal-Right Skewed", html = TRUE, class = c("html", 
    "character")), correct = TRUE, message = NULL, type = "literal"), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_6426975", 
    option = "Bimodal-Right Skewed", value = "Bimodal-Right Skewed", 
    label = structure("Bimodal-Right Skewed", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL, type = "literal"), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_96ce458", 
    option = "Unimodal-Left Skewed", value = "Unimodal-Left Skewed", 
    label = structure("Unimodal-Left Skewed", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL, type = "literal"), class = c("tutorial_question_answer", 
"tutorial_quiz_answer"))), button_labels = list(submit = structure("<span data-i18n=\"button.questionsubmit\">Submit Answer<\u002fspan>", html = TRUE, class = c("html", 
"character")), try_again = structure("<span data-i18n=\"button.questiontryagain\">Try Again<\u002fspan>", html = TRUE, class = c("html", 
"character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", 
"character")), try_again = structure("Incorrect", html = TRUE, class = c("html", 
"character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", 
"character")), message = NULL, post_message = NULL), ids = list(
    answer = "quiz3-1-answer", question = "quiz3-1"), loading = NULL, 
    random_answer_order = FALSE, allow_retry = FALSE, seed = 1527179196.28885, 
    options = list()), class = c("learnr_radio", "tutorial_question"
)), session = session)
</script>


<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz44-1", question = structure("Which interpretation might be correct for the output above?", html = TRUE, class = c("html", 
"character")), answers = list(structure(list(id = "lnr_ans_abc664c", 
    option = "A different assocition between price and carat for each clarity type is observed they have strong negative and weak positive associations", 
    value = "A different assocition between price and carat for each clarity type is observed they have strong negative and weak positive associations", 
    label = structure("A different assocition between price and carat for each clarity type is observed they have strong negative and weak positive associations", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL, type = "literal"), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_a096320", 
    option = "A similar assocition between price and carat for each clarity type is observed they have a weak and positive association ", 
    value = "A similar assocition between price and carat for each clarity type is observed they have a weak and positive association ", 
    label = structure("A similar assocition between price and carat for each clarity type is observed they have a weak and positive association", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL, type = "literal"), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_ee1a6a0", 
    option = "A similar assocition between price and carat for each clarity type is observed they have a strong and positive association ", 
    value = "A similar assocition between price and carat for each clarity type is observed they have a strong and positive association ", 
    label = structure("A similar assocition between price and carat for each clarity type is observed they have a strong and positive association", html = TRUE, class = c("html", 
    "character")), correct = TRUE, message = NULL, type = "literal"), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_22815e7", 
    option = "A similar assocition between price and carat for each clarity type is observed they have a weak but positive association", 
    value = "A similar assocition between price and carat for each clarity type is observed they have a weak but positive association", 
    label = structure("A similar assocition between price and carat for each clarity type is observed they have a weak but positive association", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL, type = "literal"), class = c("tutorial_question_answer", 
"tutorial_quiz_answer"))), button_labels = list(submit = structure("<span data-i18n=\"button.questionsubmit\">Submit Answer<\u002fspan>", html = TRUE, class = c("html", 
"character")), try_again = structure("<span data-i18n=\"button.questiontryagain\">Try Again<\u002fspan>", html = TRUE, class = c("html", 
"character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", 
"character")), try_again = structure("Incorrect", html = TRUE, class = c("html", 
"character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", 
"character")), message = NULL, post_message = NULL), ids = list(
    answer = "quiz44-1-answer", question = "quiz44-1"), loading = NULL, 
    random_answer_order = FALSE, allow_retry = FALSE, seed = 1110725651.48278, 
    options = list()), class = c("learnr_radio", "tutorial_question"
)), session = session)
</script>
</p>
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["header-attrs"]},{"type":"character","attributes":{},"value":["2.20"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pandoc"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["header-attrs.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.20"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.1.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/cerulean.min.css"]},{"type":"character","attributes":{},"value":["<style>h1 {font-size: 34px;}\n       h1.title {font-size: 38px;}\n       h2 {font-size: 30px;}\n       h3 {font-size: 24px;}\n       h4 {font-size: 18px;}\n       h5 {font-size: 16px;}\n       h6 {font-size: 12px;}\n       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}\n       pre:not([class]) { background-color: white }<\/style>"]},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.20"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.20"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.20"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.11.2"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.11.2"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["i18n"]},{"type":"character","attributes":{},"value":["21.6.10"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/i18n"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["i18next.min.js","tutorial-i18n-init.js"]},{"type":"NULL"},{"type":"character","attributes":{},"value":["<script id=\"i18n-cstm-trns\" type=\"application/json\">{\"language\":\"en\",\"resources\":{\"en\":{\"translation\":{\"button\":{\"runcode\":\"Run Code\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Hint\",\"hint_plural\":\"Hints\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Next Hint\",\"hintprev\":\"Previous Hint\",\"solution\":\"Solution\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Copy to Clipboard\",\"startover\":\"Start Over\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Continue\",\"submitanswer\":\"Submit Answer\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Previous Topic\",\"nexttopic\":\"Next Topic\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Try Again\"},\"text\":{\"startover\":\"Start Over\",\"areyousure\":\"Are you sure you want to start over? (all exercise progress will be reset)\",\"youmustcomplete\":\"You must complete the\",\"exercise\":\"exercise\",\"exercise_plural\":\"exercises\",\"inthissection\":\"in this section before continuing.\",\"code\":\"Code\",\"enginecap\":\"{{engine}} $t(text.code)\",\"quiz\":\"Quiz\",\"blank\":\"blank\",\"blank_plural\":\"blanks\",\"exercisecontainsblank\":\"This exercise contains {{count}} $t(text.blank).\",\"pleasereplaceblank\":\"Please replace {{blank}} with valid code.\",\"unparsable\":\"It looks like this might not be valid R code. R cannot determine how to turn your text into a complete command. You may have forgotten to fill in a blank, to remove an underscore, to include a comma between arguments, or to close an opening <code>&quot;<\\/code>, <code>'<\\/code>, <code>(<\\/code> or <code>{<\\/code> with a matching <code>&quot;<\\/code>, <code>'<\\/code>, <code>)<\\/code> or <code>}<\\/code>.\\n\",\"unparsablequotes\":\"<p>It looks like your R code contains specially formatted quotation marks or &quot;curly&quot; quotes (<code>{{character}}<\\/code>) around character strings, making your code invalid. R requires character values to be contained in straight quotation marks (<code>&quot;<\\/code> or <code>'<\\/code>).<\\/p> {{code}} <p>Don't worry, this is a common source of errors when you copy code from another app that applies its own formatting to text. You can try replacing the code on that line with the following. There may be other places that need to be fixed, too.<\\/p> {{suggestion}}\\n\",\"unparsableunicode\":\"<p>It looks like your R code contains an unexpected special character (<code>{{character}}<\\/code>) that makes your code invalid.<\\/p> {{code}} <p>Sometimes your code may contain a special character that looks like a regular character, especially if you copy and paste the code from another app. Try deleting the special character from your code and retyping it manually.<\\/p>\\n\",\"unparsableunicodesuggestion\":\"<p>It looks like your R code contains an unexpected special character (<code>{{character}}<\\/code>) that makes your code invalid.<\\/p> {{code}} <p>Sometimes your code may contain a special character that looks like a regular character, especially if you copy and paste the code from another app. You can try replacing the code on that line with the following. There may be other places that need to be fixed, too.<\\/p> {{suggestion}}\\n\",\"and\":\"and\",\"or\":\"or\",\"listcomma\":\", \",\"oxfordcomma\":\",\"}}},\"fr\":{\"translation\":{\"button\":{\"runcode\":\"Lancer le Code\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Indication\",\"hint_plural\":\"Indications\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Indication Suivante\",\"hintprev\":\"Indication Précédente\",\"solution\":\"Solution\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Copier dans le Presse-papier\",\"startover\":\"Recommencer\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Continuer\",\"submitanswer\":\"Soumettre\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Chapitre Précédent\",\"nexttopic\":\"Chapitre Suivant\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Réessayer\"},\"text\":{\"startover\":\"Recommencer\",\"areyousure\":\"Êtes-vous certains de vouloir recommencer? (La progression sera remise à zéro)\",\"youmustcomplete\":\"Vous devez d'abord compléter\",\"exercise\":\"l'exercice\",\"exercise_plural\":\"des exercices\",\"inthissection\":\"de cette section avec de continuer.\",\"code\":\"Code\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Quiz\",\"and\":\"et\",\"or\":\"ou\",\"oxfordcomma\":\"\"}}},\"es\":{\"translation\":{\"button\":{\"runcode\":\"Ejecutar código\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Pista\",\"hint_plural\":\"Pistas\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Siguiente pista\",\"hintprev\":\"Pista anterior\",\"solution\":\"Solución\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Copiar al portapapeles\",\"startover\":\"Reiniciar\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Continuar\",\"submitanswer\":\"Enviar respuesta\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Tema anterior\",\"nexttopic\":\"Tema siguiente\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Volver a intentar\"},\"text\":{\"startover\":\"Reiniciar\",\"areyousure\":\"¿De verdad quieres empezar de nuevo? (todo el progreso del ejercicio se perderá)\",\"youmustcomplete\":\"Debes completar\",\"exercise\":\"el ejercicio\",\"exercise_plural\":\"los ejercicios\",\"inthissection\":\"en esta sección antes de continuar.\",\"code\":\"Código\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Cuestionario\",\"and\":\"y\",\"or\":\"o\",\"oxfordcomma\":\"\"}}},\"pt\":{\"translation\":{\"button\":{\"runcode\":\"Executar código\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Dica\",\"hint_plural\":\"Dicas\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Próxima dica\",\"hintprev\":\"Dica anterior\",\"solution\":\"Solução\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Copiar para a área de transferência\",\"startover\":\"Reiniciar\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Continuar\",\"submitanswer\":\"Enviar resposta\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Tópico anterior\",\"nexttopic\":\"Próximo tópico\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Tentar novamente\"},\"text\":{\"startover\":\"Reiniciar\",\"areyousure\":\"Tem certeza que deseja começar novamente? (todo o progresso feito será perdido)\",\"youmustcomplete\":\"Você deve completar\",\"exercise\":\"o exercício\",\"exercise_plural\":\"os exercícios\",\"inthissection\":\"nesta seção antes de continuar.\",\"code\":\"Código\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Quiz\",\"and\":\"e\",\"or\":\"ou\",\"oxfordcomma\":\"\"}}},\"tr\":{\"translation\":{\"button\":{\"runcode\":\"Çalıştırma Kodu\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Ipucu\",\"hint_plural\":\"İpuçları\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Sonraki İpucu\",\"hintprev\":\"Önceki İpucu\",\"solution\":\"Çözüm\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Pano'ya Kopyala\",\"startover\":\"Baştan Başlamak\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Devam et\",\"submitanswer\":\"Cevabı onayla\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Önceki Konu\",\"nexttopic\":\"Sonraki Konu\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Tekrar Deneyin\"},\"text\":{\"startover\":\"Baştan Başlamak\",\"areyousure\":\"Baştan başlamak istediğinizden emin misiniz? (tüm egzersiz ilerlemesi kaybolacak)\",\"youmustcomplete\":\"Tamamlamalısın\",\"exercise\":\"egzersiz\",\"exercise_plural\":\"egzersizler\",\"inthissection\":\"devam etmeden önce bu bölümde\",\"code\":\"Kod\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Sınav\",\"oxfordcomma\":\"\"}}},\"emo\":{\"translation\":{\"button\":{\"runcode\":\"<U+0001F3C3>\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"<U+0001F4A1>\",\"hint_plural\":\"$t(button.hint)\",\"hinttitle\":\"$t(button.hint)\",\"solution\":\"<U+0001F3AF>\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"<U+0001F4CB>\",\"startover\":\"<U+23EE>\",\"startovertitle\":\"Start Over\",\"continue\":\"<U+2705>\",\"submitanswer\":\"<U+0001F197>\",\"submitanswertitle\":\"Submit Answer\",\"previoustopic\":\"<U+2B05>\",\"nexttopic\":\"<U+27A1>\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"<U+0001F501>\"},\"text\":{\"startover\":\"<U+23EE>\",\"areyousure\":\"<U+0001F914>\",\"youmustcomplete\":\"<U+26A0><U+FE0F> <U+0001F449> <U+0001F9D1><U+200D><U+0001F4BB>\",\"exercise\":\"\",\"exercise_plural\":\"\",\"inthissection\":\"\",\"code\":\"<U+0001F4BB>\",\"enginecap\":\"$t(text.code) {{engine}}\",\"oxfordcomma\":\"\"}}},\"eu\":{\"translation\":{\"button\":{\"runcode\":\"Kodea egikaritu\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Laguntza\",\"hint_plural\":\"Laguntza\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Aurreko laguntza\",\"hintprev\":\"Hurrengo laguntza\",\"solution\":\"Ebazpena\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Arbelean kopiatu\",\"startover\":\"Berrabiarazi\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Jarraitu\",\"submitanswer\":\"Erantzuna bidali\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Aurreko atala\",\"nexttopic\":\"Hurrengo atala\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Berriro saiatu\"},\"text\":{\"startover\":\"Berrabiarazi\",\"areyousure\":\"Berriro hasi nahi duzu? (egindako lana galdu egingo da)\",\"youmustcomplete\":\"Aurrera egin baino lehen atal honetako\",\"exercise\":\"ariketa egin behar duzu.\",\"exercise_plural\":\"ariketak egin behar dituzu.\",\"inthissection\":\"\",\"code\":\"Kodea\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Galdetegia\",\"oxfordcomma\":\"\"}}},\"de\":{\"translation\":{\"button\":{\"runcode\":\"Code ausführen\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Tipp\",\"hint_plural\":\"Tipps\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Nächster Tipp\",\"hintprev\":\"Vorheriger Tipp\",\"solution\":\"Lösung\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"In die Zwischenablage kopieren\",\"startover\":\"Neustart\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Weiter\",\"submitanswer\":\"Antwort einreichen\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Vorheriges Kapitel\",\"nexttopic\":\"Nächstes Kapitel\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Nochmal versuchen\"},\"text\":{\"startover\":\"Neustart\",\"areyousure\":\"Bist du sicher, dass du neustarten willst? (der gesamte Lernfortschritt wird gelöscht)\",\"youmustcomplete\":\"Vervollstädinge\",\"exercise\":\"die Übung\",\"exercise_plural\":\"die Übungen\",\"inthissection\":\"in diesem Kapitel, bevor du fortfährst.\",\"code\":\"Code\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Quiz\",\"blank\":\"Lücke\",\"blank_plural\":\"Lücken\",\"pleasereplaceblank\":\"Bitte ersetze {{blank}} mit gültigem Code.\",\"unparsable\":\"Dies scheint kein gültiger R Code zu sein. R kann deinen Text nicht in einen gültigen Befehl übersetzen. Du hast vielleicht vergessen, die Lücke zu füllen, einen Unterstrich zu entfernen, ein Komma zwischen Argumente zu setzen oder ein eröffnendes <code>&quot;<\\/code>, <code>'<\\/code>, <code>(<\\/code> oder <code>{<\\/code> mit einem zugehörigen <code>&quot;<\\/code>, <code>'<\\/code>, <code>)<\\/code> oder <code>}<\\/code> zu schließen.\\n\",\"and\":\"und\",\"or\":\"oder\",\"listcomma\":\", \",\"oxfordcomma\":\",\"}}},\"ko\":{\"translation\":{\"button\":{\"runcode\":\"<U+CF54><U+B4DC> <U+C2E4><U+D589>\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"<U+D78C><U+D2B8>\",\"hint_plural\":\"<U+D78C><U+D2B8><U+B4E4>\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"<U+B2E4><U+C74C> <U+D78C><U+D2B8>\",\"hintprev\":\"<U+C774><U+C804> <U+D78C><U+D2B8>\",\"solution\":\"<U+C194><U+B8E8><U+C158>\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"<U+D074><U+B9BD><U+BCF4><U+B4DC><U+C5D0> <U+BCF5><U+C0AC>\",\"startover\":\"<U+C7AC><U+D559><U+C2B5>\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"<U+B2E4><U+C74C> <U+D559><U+C2B5><U+C73C><U+B85C>\",\"submitanswer\":\"<U+C815><U+B2F5> <U+C81C><U+CD9C>\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"<U+C774><U+C804> <U+D1A0><U+D53D>\",\"nexttopic\":\"<U+B2E4><U+C74C> <U+D1A0><U+D53D>\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"<U+C7AC><U+C2DC><U+B3C4>\"},\"text\":{\"startover\":\"<U+C7AC><U+D559><U+C2B5>\",\"areyousure\":\"<U+B2E4><U+C2DC> <U+C2DC><U+C791> <U+D558><U+C2DC><U+ACA0><U+C2B5><U+B2C8><U+AE4C>? (<U+BAA8><U+B4E0> <U+C608><U+C81C><U+C758> <U+C9C4><U+D589> <U+C815><U+BCF4><U+AC00> <U+C7AC><U+C124><U+C815><U+B429><U+B2C8><U+B2E4>)\",\"youmustcomplete\":\"<U+B2F9><U+C2E0><U+C740> <U+C644><U+B8CC><U+D574><U+C57C> <U+D569><U+B2C8><U+B2E4>\",\"exercise\":\"<U+C5F0><U+C2B5><U+BB38><U+C81C>\",\"exercise_plural\":\"<U+C5F0><U+C2B5><U+BB38><U+C81C><U+B4E4>\",\"inthissection\":\"<U+C774> <U+C139><U+C158><U+C744> <U+C2E4><U+D589><U+D558><U+AE30> <U+C804><U+C5D0>\",\"code\":\"<U+CF54><U+B4DC>\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"<U+D034><U+C988>\",\"blank\":\"<U+ACF5><U+BC31>\",\"blank_plural\":\"<U+ACF5><U+BC31><U+B4E4>\",\"exercisecontainsblank\":\"<U+C774> <U+C5F0><U+C2B5><U+BB38><U+C81C><U+C5D0><U+B294> {{count}}<U+AC1C><U+C758> $t(text.blank)<U+C774> <U+D3EC><U+D568><U+B418><U+C5B4> <U+C788><U+C2B5><U+B2C8><U+B2E4>.\",\"pleasereplaceblank\":\"{{blank}}<U+B97C> <U+C720><U+D6A8><U+D55C> <U+CF54><U+B4DC><U+B85C> <U+BC14><U+AFB8><U+C2ED><U+C2DC><U+C624>.\",\"unparsable\":\"<U+C774><U+AC83><U+C740> <U+C720><U+D6A8><U+D55C> R <U+CF54><U+B4DC><U+AC00> <U+C544><U+B2D0> <U+C218> <U+C788><U+C2B5><U+B2C8><U+B2E4>. R<U+C740> <U+D14D><U+C2A4><U+D2B8><U+B97C> <U+C644><U+C804><U+D55C> <U+BA85><U+B839><U+C73C><U+B85C> <U+BCC0><U+D658><U+D558><U+B294> <U+BC29><U+BC95><U+C744> <U+ACB0><U+C815><U+D560> <U+C218> <U+C5C6><U+C2B5><U+B2C8><U+B2E4>. <U+B2F9><U+C2E0><U+C740> <U+ACF5><U+BC31><U+C774><U+B098> <U+BC11><U+C904><U+C744> <U+B300><U+CCB4><U+D558><U+C5EC> <U+CC44><U+C6B0><U+AE30>, <U+C778><U+C218><U+B97C> <U+CEF4><U+B9C8><U+B85C> <U+AD6C><U+BD84><U+D558><U+AE30>, <U+B610><U+B294> <code>&quot;<\\/code>, <code>'<\\/code>, <code>(<\\/code> , <code>{<\\/code><U+B85C> <U+C2DC><U+C791><U+D558><U+B294> <U+AD6C><U+BB38><U+C744> <U+B2EB><U+B294> <code>&quot;<\\/code>, <code>'<\\/code>, <code>)<\\/code>, <code>}<\\/code><U+C744> <U+C78A><U+C5C8><U+C744> <U+C218><U+B3C4> <U+C788><U+C2B5><U+B2C8><U+B2E4>.\\n\",\"and\":\"<U+ADF8><U+B9AC><U+ACE0>\",\"or\":\"<U+D639><U+C740>\",\"listcomma\":\", \",\"oxfordcomma\":\"\"}}},\"zh\":{\"translation\":{\"button\":{\"runcode\":\"<U+8FD0><U+884C><U+4EE3><U+7801>\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"<U+63D0><U+793A>\",\"hint_plural\":\"<U+63D0><U+793A>\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"<U+4E0B><U+4E00><U+4E2A><U+63D0><U+793A>\",\"hintprev\":\"<U+4E0A><U+4E00><U+4E2A><U+63D0><U+793A>\",\"solution\":\"<U+7B54><U+6848>\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"<U+590D><U+5236><U+5230><U+526A><U+5207><U+677F>\",\"startover\":\"<U+91CD><U+65B0><U+5F00><U+59CB>\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"<U+7EE7><U+7EED>\",\"submitanswer\":\"<U+63D0><U+4EA4><U+7B54><U+6848>\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"<U+4E0A><U+4E00><U+4E13><U+9898>\",\"nexttopic\":\"<U+4E0B><U+4E00><U+4E13><U+9898>\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"<U+518D><U+8BD5><U+4E00><U+6B21>\"},\"text\":{\"startover\":\"<U+91CD><U+7F6E>\",\"areyousure\":\"<U+4F60><U+786E><U+5B9A><U+8981><U+91CD><U+65B0><U+5F00><U+59CB><U+5417>? (<U+6240><U+6709><U+5F53><U+524D><U+8FDB><U+5EA6><U+5C06><U+88AB><U+91CD><U+7F6E>)\",\"youmustcomplete\":\"<U+4F60><U+5FC5><U+987B><U+5B8C><U+6210>\",\"exercise\":\"<U+7EC3><U+4E60>\",\"exercise_plural\":\"<U+7EC3><U+4E60>\",\"inthissection\":\"<U+5728><U+8FDB><U+884C><U+672C><U+8282><U+4E4B><U+524D>\",\"code\":\"<U+4EE3><U+7801>\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"<U+6D4B><U+8BD5>\",\"blank\":\"<U+7A7A>\",\"blank_plural\":\"<U+7A7A>\",\"exercisecontainsblank\":\"<U+672C><U+7EC3><U+4E60><U+5305><U+542B>{{count}}<U+4E2A>$t(text.blank)\",\"pleasereplaceblank\":\"<U+8BF7><U+5728>{{blank}}<U+5185><U+586B><U+5199><U+6070><U+5F53><U+7684><U+4EE3><U+7801>\",\"unparsable\":\"<U+8FD9><U+4F3C><U+4E4E><U+4E0D><U+662F><U+6709><U+6548><U+7684>R<U+4EE3><U+7801><U+3002> R<U+4E0D><U+77E5><U+9053><U+5982><U+4F55><U+5C06><U+60A8><U+7684><U+6587><U+672C><U+8F6C><U+6362><U+4E3A><U+5B8C><U+6574><U+7684><U+547D><U+4EE4><U+3002> <U+60A8><U+662F><U+5426><U+5FD8><U+4E86><U+586B><U+7A7A>,<U+5FD8><U+4E86><U+5220><U+9664><U+4E0B><U+5212><U+7EBF>,<U+5FD8><U+4E86><U+5728><U+53C2><U+6570><U+4E4B><U+95F4><U+5305><U+542B><U+9017><U+53F7>,<U+6216><U+8005><U+662F><U+5FD8><U+4E86><U+7528><code>&quot;<\\/code>, <code>'<\\/code>, <code>)<\\/code>,<code>}<\\/code><U+6765><U+5C01><U+95ED><code>&quot;<\\/code>, <code>'<\\/code>, <code>(<\\/code><U+3002> or <code>{<\\/code><U+3002>\\n\",\"unparsablequotes\":\"<p><U+60A8><U+7684>R<U+4EE3><U+7801><U+4E2D><U+4F3C><U+4E4E><U+542B><U+6709><U+7279><U+6B8A><U+683C><U+5F0F><U+7684><U+5F15><U+53F7>,<U+6216><U+8005><U+5F2F><U+5F15><U+53F7>(<code>{{character}}<\\/code>) <U+5728><U+5B57><U+7B26><U+4E32><U+524D><U+540E>,<U+5728>R<U+4E2D><U+5B57><U+7B26><U+4E32><U+5E94><U+8BE5><U+88AB><U+76F4><U+5F15><U+53F7>(<code>&quot;<\\/code> <U+6216><U+8005> <code>'<\\/code>)<U+5305><U+88F9><U+3002><\\/p> {{code}} <p><U+522B><U+62C5><U+5FC3>,<U+8BE5><U+9519><U+8BEF><U+7ECF><U+5E38><U+5728><U+590D><U+5236><U+7C98><U+8D34><U+5305><U+542B><U+683C><U+5F0F><U+7684><U+4EE3><U+7801><U+65F6><U+9047><U+5230>, <U+60A8><U+53EF><U+4EE5><U+5C1D><U+8BD5><U+5C06><U+8BE5><U+884C><U+4E2D><U+7684><U+4EE3><U+7801><U+66FF><U+6362><U+4E3A><U+4EE5><U+4E0B><U+4EE3><U+7801>,<U+4E5F><U+8BB8><U+8FD8><U+6709><U+5176><U+4ED6><U+5730><U+65B9><U+9700><U+8981><U+4FEE><U+6539><U+3002><\\/p> {{suggestion}}\\n\",\"unparsableunicode\":\"<p><U+60A8><U+7684><U+4EE3><U+7801><U+4E2D><U+4F3C><U+4E4E><U+5305><U+542B><U+6709><U+5F02><U+5E38><U+5B57><U+7B26>(<code>{{character}}<\\/code>),<U+5BFC><U+81F4><U+4EE3><U+7801><U+65E0><U+6548><U+3002><\\/p> {{code}} <p><U+6709><U+65F6><U+5019><U+4F60><U+7684><U+4EE3><U+7801><U+53EF><U+80FD><U+542B><U+6709><U+770B><U+4F3C><U+6B63><U+5E38><U+5B57><U+7B26><U+7684><U+7279><U+6B8A><U+5B57><U+7B26>,<U+7279><U+522B><U+662F><U+5F53><U+4F60><U+590D><U+5236><U+7C98><U+8D34><U+5176><U+4ED6><U+6765><U+6E90><U+4EE3><U+7801><U+7684><U+65F6><U+5019><U+3002> <U+8BF7><U+8BD5><U+7740><U+5220><U+9664><U+8FD9><U+4E9B><U+7279><U+6B8A><U+5B57><U+7B26>,<U+91CD><U+65B0><U+8F93><U+5165><\\/p>\\n\",\"unparsableunicodesuggestion\":\"<p><U+60A8><U+7684><U+4EE3><U+7801><U+4E2D><U+4F3C><U+4E4E><U+5305><U+542B><U+6709><U+5F02><U+5E38><U+5B57><U+7B26>(<code>{{character}}<\\/code>),<U+5BFC><U+81F4><U+4EE3><U+7801><U+65E0><U+6548><U+3002><\\/p> {{code}} <p><U+6709><U+65F6><U+5019><U+4F60><U+7684><U+4EE3><U+7801><U+53EF><U+80FD><U+542B><U+6709><U+770B><U+4F3C><U+6B63><U+5E38><U+5B57><U+7B26><U+7684><U+7279><U+6B8A><U+5B57><U+7B26>,<U+7279><U+522B><U+662F><U+5F53><U+4F60><U+590D><U+5236><U+7C98><U+8D34><U+5176><U+4ED6><U+6765><U+6E90><U+4EE3><U+7801><U+7684><U+65F6><U+5019><U+3002> <U+8BF7><U+8BD5><U+7740><U+5220><U+9664><U+8FD9><U+4E9B><U+7279><U+6B8A><U+5B57><U+7B26>,<U+91CD><U+65B0><U+8F93><U+5165><\\/p>\\n\",\"and\":\"<U+4E14>\",\"or\":\"<U+6216>\",\"listcomma\":\",\",\"oxfordcomma\":\",\"}}},\"pl\":{\"translation\":{\"button\":{\"runcode\":\"Uruchom kod\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Podpowiedz\",\"hint_plural\":\"Podpowiedzi\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Nastepna podpowiedz\",\"hintprev\":\"Poprzednia podpowiedz\",\"solution\":\"Rozwiazanie\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Kopiuj do schowka\",\"startover\":\"Zacznij od poczatku\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Kontynuuj\",\"submitanswer\":\"Wyslij\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Poprzednia sekcja\",\"nexttopic\":\"Nastepna sekcja\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Spróbuj ponownie\"},\"text\":{\"startover\":\"Zacznij od poczatku\",\"areyousure\":\"Czy na pewno chcesz zaczac od poczatku? (caly postep w zadaniu zostanie utracony)\",\"youmustcomplete\":\"Musisz ukonczyc\",\"exercise\":\"cwiczenie\",\"exercise_plural\":\"cwiczenia\",\"inthissection\":\"w tej sekcji przed kontynuowaniem\",\"code\":\"Kod\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Quiz\",\"blank\":\"luka\",\"blank_plural\":\"luk(i)\",\"exercisecontainsblank\":\"To cwiczenie zawiera {{count}} $t(text.blank).\",\"pleasereplaceblank\":\"Prosze uzupelnic {{blank}} prawidlowym kodem.\",\"unparsable\":\"Wyglada na to, ze moze to nie byc prawidlowy kod R. R nie jest w stanie przetworzyc Twojego tekstu na polecenie. Mogles(-as) zapomniec wypelnic luki, usunac podkreslnik, umiescic przecinka miedzy argumentami, lub zamknac znak <code>&quot;<\\/code>, <code>'<\\/code>, <code>(<\\/code> lub <code>{<\\/code> odpowiadajacym <code>&quot;<\\/code>, <code>'<\\/code>, <code>)<\\/code> lub <code>}<\\/code>.\\n\",\"unparsablequotes\":\"<p>Wyglada na to, ze Twój kod zawiera szczególnie sformatowane cudzyslowy lub cudzyslowy typograficzne (<code>{{character}}<\\/code>) przy ciagach znaków, co sprawia, ze kod jest niepoprawny. R wymaga cudzyslowów prostych (<code>&quot;<\\/code> albo <code>'<\\/code>).<\\/p> {{code}} <p>Nie martw sie, to powszechne zródlo bledów, gdy kopiuje sie kod z innego programu, który sam formatuje teskt. Mozesz spróbowac zastapic swój kod nastepujacym kodem. Moga byc tez inne miejsca, które wymagaja poprawienia.<\\/p> {{suggestion}}\\n\",\"unparsableunicode\":\"<p>Wyglada na to, ze Twój kod zawiera niespodziewany znak specjalny (<code>{{character}}<\\/code>), co sprawia, ze kod jest niepoprawny.<\\/p> {{code}} <p>Czasami Twój kod moze zawierac znak specjalny, który wyglada jak zwykly znak, zwlaszcza jesli kopiujesz kod z innego programu. Spróbuj usunac znak specjalny i wpisac do ponownie recznie.<\\/p>\\n\",\"unparsableunicodesuggestion\":\"<p>Wyglada na to, ze Twój kod zawiera niespodziewany znak specjalny (<code>{{character}}<\\/code>), co sprawia, ze kod jest niepoprawny.<\\/p> {{code}} <p>Czasami Twój kod moze zawierac znak specjalny, który wyglada jak zwykly znak, zwlaszcza jesli kopiujesz kod z innego programu. Mozesz spróbowac zastapic swój kod nastepujacym kodem. Moga byc tez inne miejsca, które wymagaja poprawienia.<\\/p> {{suggestion}}\\n\",\"and\":\"i\",\"or\":\"lub\",\"listcomma\":\", \",\"oxfordcomma\":\"\"}}}}}<\/script>"]},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.11.2"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.11.2"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css","rstudio-theme.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.11.2"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.1.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.20"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.20"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.1.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.20"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["5.5.2"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.11.2"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.11.2"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.11.2"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.11.2"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["table1"]},{"type":"character","attributes":{},"value":["1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["table1_defaults_1.0"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["table1_defaults.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["table1"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.4.3"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108]}},"value":[{"type":"character","attributes":{},"value":["backports","base","base64enc","bslib","cachem","checkmate","cli","cluster","codetools","colorspace","commonmark","compiler","curl","data.table","datasets","deldir","digest","dplyr","ellipsis","evaluate","fansi","fastmap","foreign","Formula","generics","ggplot2","glue","graphics","grDevices","grid","gridExtra","gtable","highr","Hmisc","htmlTable","htmltools","htmlwidgets","httpuv","interp","jpeg","jquerylib","jsonlite","knitr","later","lattice","latticeExtra","learnr","lifecycle","lubridate","magick","magrittr","markdown","MASS","Matrix","matrixStats","methods","mime","mnormt","munsell","nlme","nnet","pander","parallel","PerformanceAnalytics","pillar","pkgconfig","plyr","png","promises","pryr","psych","purrr","quadprog","R6","rapportools","RColorBrewer","Rcpp","reshape2","rlang","rmarkdown","rpart","rprojroot","rstudioapi","sass","scales","shiny","splines","stats","stringi","stringr","summarytools","survival","table1","tcltk","tibble","tidyr","tidyselect","timechange","tools","utf8","utils","vctrs","withr","xfun","xtable","xts","yaml","zoo"]},{"type":"character","attributes":{},"value":["1.4.1","4.1.0","0.1-3","0.4.2","1.0.6","2.1.0","3.4.1","2.1.4","0.2-19","2.0-2","1.8.1","4.1.0","5.0.0","1.14.8","4.1.0","1.0-6","0.6.31","1.1.0","0.3.2","0.20","0.5.0","1.1.0","0.8-84","1.2-4","0.1.3","3.4.1","1.6.2","4.1.0","4.1.0","4.1.0","2.3","0.3.1","0.10","4.8-0","2.4.1","0.5.4","1.6.1","1.6.9","1.1-3","0.1-10","0.1.4","1.7.2","1.42","1.3.0","0.20-45","0.6-30","0.11.2","1.0.3","1.9.2","2.7.3","2.0.1","1.5","7.3-58.2","1.3-4","0.63.0","4.1.0","0.12","2.1.1","0.5.0","3.1-162","7.3-18","0.6.5","4.1.0","2.0.4","1.8.1","2.0.3","1.8.8","0.1-8","1.2.0.1","0.1.6","2.2.9","0.3.4","1.5-8","2.5.1","1.1","1.1-3","1.0.7","1.4.4","1.0.6","2.20","4.1.19","2.0.3","0.14","0.4.5","1.2.1","1.7.4","4.1.0","4.1.0","1.7.5","1.5.0","1.0.1","3.5-3","1.4.3","4.1.0","3.1.6","1.2.1","1.2.0","0.2.0","4.1.0","1.2.2","4.1.0","0.5.2","2.5.0","0.37","1.8-4","0.13.0","2.3.7","1.8-11"]}]}]}
</script>
<!--/html_preserve-->
</div>
</div>

</article> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h1 class="title toc-ignore" style="display:none;">STAT 412-Recitation
1</h1>
<h4 class="author"><em>Ozancan Ozdemir</em></h4>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</main> <!-- bandContent page -->
</div> <!-- pageContent band -->



<!-- Build Tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
